INSERT INTO `main_listed_companies` (`stock_name`, `stock_code`, `business_area`, `company_name`, `known_name`) VALUES
('KOTRA', '0002', 'Health Care, Main Market', 'KOTRA INDUSTRIES BHD', 'KOTRA'),
('WILLOW', '0008', 'Technology, Main Market', 'WILLOWGLEN MSC BHD', 'WILLOWGLEN MSC'),
('3A', '0012', 'Consumer Products & Services, Main Market', 'THREE-A RESOURCES BHD', 'THREE-A'),
('GHLSYS', '0021', 'Technology, Main Market', 'GHL SYSTEMS BHD', 'GHL SYSTEMS'),
('DIGISTA', '0029', 'Technology, Main Market', 'DIGISTAR CORPORATION BHD', 'DIGISTAR'),
('RGB', '0037', 'Consumer Products & Services, Main Market', 'RGB INTERNATIONAL BHD', 'RGB INTERNATIONAL'),
('MYSCM', '0041', 'Technology, Main Market', 'MSCM HOLDINGS BERHAD', 'MSCM'),
('MTRONIC', '0043', 'Industrial Products & Services, Main Market', 'METRONIC GLOBAL BHD', 'METRONIC GLOBAL'),
('PERISAI', '0047', 'Energy, Main Market', 'PERISAI PETROLEUM TEKNOLOGI', 'PERISAI PETROLEUM TEKNOLOGI'),
('OCNCASH', '0049', 'Consumer Products & Services, Main Market', 'OCEANCASH PACIFIC BHD', 'OCEANCASH PACIFIC'),
('CUSCAPI', '0051', 'Technology, Main Market', 'CUSCAPI BHD', 'CUSCAPI'),
('KARYON', '0054', 'Industrial Products & Services, Main Market', 'KARYON INDUSTRIES BHD', 'KARYON'),
('GRANFLO', '0056', 'Technology, Main Market', 'GRAND-FLO BERHAD', 'GRAND-FLO'),
('JCBNEXT', '0058', 'Industrial Products & Services, Main Market', 'JCBNEXT BERHAD', 'JCBNEXT'),
('ECOHLDS', '0059', 'Telecommunications & Media, Main Market', 'ECOBUILT HOLDINGS BERHAD', 'ECOBUILT'),
('EFFICEN', '0064', 'Industrial Products & Services, Main Market', 'EFFICIENT E-SOLUTIONS BHD', 'EFFICIENT E-SOLUTIONS'),
('EFORCE', '0065', 'Technology, Main Market', 'EXCEL FORCE MSC BHD', 'EXCEL FORCE MSC'),
('GDEX', '0078', 'Transportation & Logistics, Main Market', 'GD EXPRESS CARRIER BHD', 'GD EX CARRIER'),
('GPACKET', '0082', 'Telecommunications & Media, Main Market', 'GREEN PACKET BHD', 'GREEN PACKET'),
('NOTION', '0083', 'Technology, Main Market', 'NOTION VTEC BHD', 'NOTION VTEC'),
('ELSOFT', '0090', 'Technology, Main Market', 'ELSOFT RESEARCH BHD', 'ELSOFT RESEARCH'),
('DAYA', '0091', 'Energy, Main Market', 'DAYA MATERIALS BHD', 'DAYA MATERIALS'),
('VITROX', '0097', 'Technology, Main Market', 'VITROX CORPORATION BHD', 'VITROX'),
('SCICOM', '0099', 'Industrial Products & Services, Main Market', 'SCICOM (MSC) BHD', 'SCICOM (MSC)'),
('TMCLIFE', '0101', 'Health Care, Main Market', 'TMC LIFE SCIENCES BHD', 'TMC LIFE SCIENCES'),
('MMSV', '0113', 'Technology, Main Market', 'MMS VENTURES BHD', 'MMS VENTURES'),
('TRIVE', '0118', 'Technology, Main Market', 'TRIVE PROPERTY GROUP BERHAD', 'TRIVE PROPERTY'),
('FRONTKN', '0128', 'Technology, Main Market', 'FRONTKEN CORPORATION BHD', 'FRONTKEN'),
('GREENYB', '0136', 'Consumer Products & Services, Main Market', 'GREENYIELD BHD', 'GREENYIELD'),
('MYEG', '0138', 'Technology, Main Market', 'MY E.G. SERVICES BHD', 'MY E.G. SERVICES'),
('KEYASIC', '0143', 'Technology, Main Market', 'KEY ASIC BHD', 'KEY ASIC'),
('FIBON', '0149', 'Industrial Products & Services, Main Market', 'FIBON BERHAD', 'FIBON'),
('KGB', '0151', 'Industrial Products & Services, Main Market', 'KELINGTON GROUP BERHAD', 'KELINGTON'),
('AMEDIA', '0159', 'Telecommunications & Media, Main Market', 'ASIA MEDIA GROUP BERHAD', 'ASIA MEDIA'),
('INARI', '0166', 'Technology, Main Market', 'INARI AMERTRON BERHAD', 'INARI AMERTRON'),
('BOILERM', '0168', 'Industrial Products & Services, Main Market', 'BOILERMECH HOLDINGS BHD', 'BOILERMECH'),
('OCK', '0172', 'Telecommunications & Media, Main Market', 'OCK GROUP BERHAD', 'OCK'),
('SALUTE', '0183', 'Consumer Products & Services, Main Market', 'SALUTICA BERHAD', 'SALUTICA'),
('HSSEB', '0185', 'Industrial Products & Services, Main Market', 'HSS ENGINEERS BERHAD', 'HSS ENGINEERS'),
('PTRANS', '0186', 'Consumer Products & Services, Main Market', 'PERAK TRANSIT BERHAD', 'PERAK TRANSIT'),
('INTA', '0192', 'Construction, Main Market', 'INTA BINA GROUP BERHAD', 'INTA BINA'),
('AMPROP', '1007', 'Property, Main Market', 'AMCORP PROPERTIES BERHAD', 'AMCORP PROPERTIES'),
('AMBANK', '1015', 'Financial Services, Main Market', 'AMMB HOLDINGS BHD', 'AMMB'),
('CIMB', '1023', 'Financial Services, Main Market', 'CIMB GROUP HOLDINGS BERHAD', 'CIMB'),
('MANULFE', '1058', 'Financial Services, Main Market', 'MANULIFE HOLDINGS BERHAD', 'MANULIFE'),
('RHBBANK', '1066', 'Financial Services, Main Market', 'RHB BANK BERHAD', 'RHB BANK'),
('HLFG', '1082', 'Financial Services, Main Market', 'HONG LEONG FINANCIAL GROUP BHD', 'HONG LEONG FINANCIAL'),
('GOB', '1147', 'Property, Main Market', 'GLOBAL ORIENTAL BERHAD', 'GLOBAL ORIENTAL'),
('MAYBANK', '1155', 'Financial Services, Main Market', 'MALAYAN BANKING BHD', 'MALAYAN BANKING'),
('ALLIANZ', '1163', 'Financial Services, Main Market', 'ALLIANZ MALAYSIA BHD', 'ALLIANZ MALAYSIA'),
('ALLIANZ-PA', '1163PA', 'Financial Services - Main Market', 'ALLIANZ MALAYSIA BHD-ICPS', 'ALLIANZ MALAYSIA -ICPS'),
('MBSB', '1171', 'Financial Services, Main Market', 'MALAYSIA BUILDING SOCIETY BHD', 'MALAYSIA BUILDING SOCIETY'),
('MAA', '1198', 'Financial Services, Main Market', 'MAA GROUP BERHAD', 'MAA'),
('SUMATEC', '1201', 'Energy, Main Market', 'SUMATEC RESOURCES BHD', 'SUMATEC'),
('PMHLDG', '1287', 'Consumer Products & Services, Main Market', 'PAN MALAYSIA HOLDINGS BHD', 'PAN MALAYSIA'),
('PBBANK', '1295', 'Financial Services, Main Market', 'PUBLIC BANK BHD', 'PUBLIC BANK'),
('EDGENTA', '1368', 'Industrial Products & Services, Main Market', 'UEM EDGENTA BERHAD', 'UEM EDGENTA'),
('ASB', '1481', 'Consumer Products & Services, Main Market', 'ADVANCE SYNERGY BHD', 'ADVANCE SYNERGY'),
('GUOCO', '1503', 'Property, Main Market', 'GUOCOLAND (MALAYSIA) BHD', 'GUOCOLAND (MALAYSIA)'),
('SYMLIFE', '1538', 'Property, Main Market', 'SYMPHONY LIFE BERHAD', 'SYMPHONY LIFE'),
('BJTOTO', '1562', 'Consumer Products & Services, Main Market', 'BERJAYA SPORTS TOTO BHD', 'BERJAYA SPORTS TOTO'),
('IWCITY', '1589', 'Property, Main Market', 'ISKANDAR WATERFRONT CITY BERHAD', 'ISKANDAR WATERFRONT CITY'),
('DRBHCOM', '1619', 'Consumer Products & Services, Main Market', 'DRB-HICOM BHD', 'DRB-HICOM'),
('LANDMRK', '1643', 'Consumer Products & Services, Main Market', 'LANDMARKS BHD', 'LANDMARKS'),
('MRCB', '1651', 'Property, Main Market', 'MALAYSIAN RESOURCES CORPORATION BERHAD', 'MALAYSIAN'),
('MENANG', '1694', 'Property, Main Market', 'MENANG CORPORATION (M) BHD', 'MENANG  (M)'),
('PARAMON', '1724', 'Property, Main Market', 'PARAMOUNT CORPORATION BHD', 'PARAMOUNT'),
('SPB', '1783', 'Property, Main Market', 'SELANGOR PROPERTIES BHD', 'SELANGOR PROPERTIES'),
('BURSA', '1818', 'Financial Services, Main Market', 'BURSA MALAYSIA BHD', 'BURSA MALAYSIA'),
('BKAWAN', '1899', 'Plantation, Main Market', 'BATU KAWAN BHD', 'BATU KAWAN'),
('PINEPAC', '1902', 'Plantation, Main Market', 'PINEHILL PACIFIC BERHAD', 'PINEHILL PACIFIC'),
('CHINTEK', '1929', 'Plantation, Main Market', 'CHIN TECK PLANTATIONS BHD', 'CHIN TECK PLANTATIONS'),
('IOICORP', '1961', 'Plantation, Main Market', 'IOI CORPORATION BHD', 'IOI'),
('KRETAM', '1996', 'Plantation, Main Market', 'KRETAM HOLDINGS BHD', 'KRETAM'),
('NSOP', '2038', 'Plantation, Main Market', 'NEGRI SEMBILAN OIL PALMS BHD', 'NEGRI SEMBILAN OIL PALMS'),
('TDM', '2054', 'Plantation, Main Market', 'TDM BHD', 'TDM'),
('HARBOUR', '2062', 'Transportation & Logistics, Main Market', 'HARBOUR-LINK GROUP BHD', 'HARBOUR-LINK'),
('UTDPLT', '2089', 'Plantation, Main Market', 'UNITED PLANTATIONS BHD', 'UNITED PLANTATIONS'),
('EASTLND', '2097', 'Consumer Products & Services, Main Market', 'EASTLAND EQUITY BHD', 'EASTLAND EQUITY'),
('COMFORT', '2127', 'Industrial Products & Services, Main Market', 'COMFORT GLOVES BERHAD', 'COMFORT GLOVES'),
('GOPENG', '2135', 'Plantation, Main Market', 'GOPENG BHD', 'GOPENG'),
('ECM', '2143', 'Financial Services, Main Market', 'ECM LIBRA FINANCIAL GRP BHD', 'ECM LIBRA FINANCIAL GRP'),
('KUCHAI', '2186', 'Financial Services, Main Market', 'KUCHAI DEVELOPMENT BHD', 'KUCHAI DEVELOPMENT'),
('MMCCORP', '2194', 'Transportation & Logistics, Main Market', 'MMC CORPORATION BHD', 'MMC'),
('IJMPLNT', '2216', 'Plantation, Main Market', 'IJM PLANTATIONS BHD', 'IJM PLANTATIONS'),
('SDRED', '2224', 'Property, Main Market', 'SELANGOR DREDGING BHD', 'SELANGOR DREDGING'),
('TALAMT', '2259', 'Property, Main Market', 'TALAM TRANSFORM BERHAD', 'TALAM TRANSFORM'),
('ZELAN', '2283', 'Construction, Main Market', 'ZELAN BHD', 'ZELAN'),
('GENP', '2291', 'Plantation, Main Market', 'GENTING PLANTATIONS BERHAD', 'GENTING PLANTATIONS'),
('AYER', '2305', 'Property, Main Market', 'AYER HOLDINGS BERHAD', 'AYER'),
('TANCO', '2429', 'Property, Main Market', 'TANCO HOLDINGS BHD', 'TANCO'),
('KLK', '2445', 'Plantation, Main Market', 'KUALA LUMPUR KEPONG BHD', 'KUALA LUMPUR KEPONG'),
('KLUANG', '2453', 'Plantation, Main Market', 'KLUANG RUBBER CO (M) BHD', 'KLUANG RUBBER CO (M)'),
('ABMB', '2488', 'Financial Services, Main Market', 'ALLIANCE BANK MALAYSIA BERHAD', 'ALLIANCE BANK MALAYSIA'),
('RVIEW', '2542', 'Plantation, Main Market', 'RIVERVIEW RUBBER ESTATES BHD', 'RIVERVIEW RUBBER ESTATES'),
('SBAGAN', '2569', 'Plantation, Main Market', 'SUNGEI BAGAN RUBBER CO (M) BHD', 'SUNGEI BAGAN RUBBER CO (M)'),
('YTLLAND', '2577', 'Property, Main Market', 'YTL LAND & DEVELOPMENT BHD', 'YTL LAND & DEVELOPMENT'),
('UMCCA', '2593', 'Plantation, Main Market', 'UNITED MALACCA BHD', 'UNITED MALACCA'),
('INCKEN', '2607', 'Plantation, Main Market', 'INCH KENNETH KAJANG RUBBER PLC', 'INCH KENNETH KAJANG RUBBER PLC'),
('AJI', '2658', 'Consumer Products & Services, Main Market', 'AJINOMOTO (M) BHD', 'AJINOMOTO (M)'),
('ALCOM', '2674', 'Industrial Products & Services, Main Market', 'ALCOM GROUP BERHAD', 'ALCOM'),
('AISB', '2682', 'Industrial Products & Services, Main Market', 'AMALGAMATED INDUSTRIAL STEEL', 'AMALGAMATED USTRIAL STEEL'),
('HUAAN', '2739', 'Energy, Main Market', 'SINO HUA-AN INTERNATIONAL BHD', 'SINO HUA-AN INTERNATIONAL'),
('FCW', '2755', 'Consumer Products & Services, Main Market', 'FCW HOLDINGS BHD', 'FCW'),
('BSTEAD', '2771', 'Industrial Products & Services, Main Market', 'BOUSTEAD HOLDINGS BHD', 'BOUSTEAD'),
('CIHLDG', '2828', 'Consumer Products & Services, Main Market', 'C.I. HOLDINGS BHD', 'C.I.'),
('CARLSBG', '2836', 'Consumer Products & Services, Main Market', 'CARLSBERG BREWERY MALAYSIA BHD', 'CARLSBERG BREWERY MALAYSIA'),
('CMSB', '2852', 'Industrial Products & Services, Main Market', 'CAHYA MATA SARAWAK BHD', 'CAHYA MATA SARAWAK'),
('CCM', '2879', 'Industrial Products & Services, Main Market', 'CHEMICAL COMPANY OF MALAYSIA', 'CHEMICAL COMPANY OF MALAYSIA'),
('CCB', '2925', 'Consumer Products & Services, Main Market', 'CYCLE & CARRIAGE BINTANG BHD', 'CYCLE & CARRIAGE BINTANG'),
('FACBIND', '2984', 'Industrial Products & Services, Main Market', 'FACB INDUSTRIES INCORPORATED', 'FACB  INCORPORATED'),
('OLYMPIA', '3018', 'Consumer Products & Services, Main Market', 'OLYMPIA INDUSTRIES BHD', 'OLYMPIA'),
('DLADY', '3026', 'Consumer Products & Services, Main Market', 'DUTCH LADY MILK INDUSTRIES BHD', 'DUTCH LADY MILK'),
('HAPSENG', '3034', 'Industrial Products & Services, Main Market', 'HAP SENG CONSOLIDATED BHD', 'HAP SENG CONSOLIDATED'),
('PETRONM', '3042', 'Energy, Main Market', 'PETRON MALAYSIA REFINING & MARKETING BERHAD', 'PETRON MALAYSIA REFINING & MARKETING'),
('MFCB', '3069', 'Utilities, Main Market', 'MEGA FIRST CORPORATION BHD', 'MEGA FIRST'),
('FIMACOR', '3107', 'Industrial Products & Services, Main Market', 'FIMA CORPORATION BHD', 'FIMA'),
('KBUNAI', '3115', 'Property, Main Market', 'KARAMBUNAI CORP BHD', 'KARAMBUNAI CORP'),
('YNHPROP', '3158', 'Property, Main Market', 'YNH PROPERTY BHD', 'YNH PROPERTY'),
('L&G', '3174', 'Property, Main Market', NULL, NULL),
('GENTING', '3182', 'Consumer Products & Services, Main Market', 'GENTING BHD', 'GENTING'),
('GKENT', '3204', 'Construction, Main Market', 'GEORGE KENT (M) BHD', 'GEORGE KENT (M)'),
('BJASSET', '3239', 'Property, Main Market', 'BERJAYA ASSETS BERHAD', 'BERJAYA ASSETS'),
('GUH', '3247', 'Industrial Products & Services, Main Market', 'GUH HOLDINGS BHD', 'GUH'),
('HEIM', '3255', 'Consumer Products & Services, Main Market', 'HEINEKEN MALAYSIA BERHAD', 'HEINEKEN MALAYSIA'),
('HEXZA', '3298', 'Industrial Products & Services, Main Market', 'HEXZA CORPORATION BHD', 'HEXZA'),
('HLIND', '3301', 'Consumer Products & Services, Main Market', 'HONG LEONG INDUSTRIES BHD', 'HONG LEONG'),
('IJM', '3336', 'Construction, Main Market', 'IJM CORPORATION BHD', 'IJM'),
('INSAS', '3379', 'Financial Services, Main Market', 'INSAS BHD', 'INSAS'),
('BJCORP', '3395', 'Industrial Products & Services, Main Market', 'BERJAYA CORPORATION BHD', 'BERJAYA'),
('E&O', '3417', 'Property, Main Market', NULL, NULL),
('JOHAN', '3441', 'Financial Services, Main Market', 'JOHAN HOLDINGS BHD', 'JOHAN'),
('KSENG', '3476', 'Industrial Products & Services, Main Market', 'KECK SENG (M) BHD', 'KECK SENG (M)'),
('DBHD', '3484', 'Property, Main Market', 'DAMANSARA REALTY BHD', 'DAMANSARA REALTY'),
('MARCO', '3514', 'Consumer Products & Services, Main Market', 'MARCO HOLDINGS BHD', 'MARCO'),
('KIANJOO', '3522', 'Industrial Products & Services, Main Market', 'KIAN JOO CAN FACTORY BHD', 'KIAN JOO CAN FACTORY'),
('ECOFIRS', '3557', 'Property, Main Market', 'ECOFIRST CONSOLIDATED BHD', 'ECOFIRST CONSOLIDATED'),
('WCEHB', '3565', 'Construction, Main Market', 'WCE HOLDINGS BERHAD', 'WCE'),
('LIENHOE', '3573', 'Property, Main Market', 'LIEN HOE CORPORATION BHD', 'LIEN HOE'),
('PGLOBE', '3611', 'Industrial Products & Services, Main Market', 'PARAGON GLOBE BERHAD', 'PARAGON GLOBE'),
('MFLOUR', '3662', 'Consumer Products & Services, Main Market', 'MALAYAN FLOUR MILLS BHD', 'MALAYAN FLOUR MILLS'),
('F&N', '3689', 'Consumer Products & Services, Main Market', NULL, NULL),
('PANAMY', '3719', 'Consumer Products & Services, Main Market', 'PANASONIC MANUFACTURING MSIA', 'PANASONIC MANUFACTURING MSIA'),
('SUNSURIA', '3743', 'Property, Main Market', 'SUNSURIA BERHAD', 'SUNSURIA'),
('MELEWAR', '3778', 'Industrial Products & Services, Main Market', 'MELEWAR INDUSTRIAL GROUP BHD', 'MELEWAR USTRIAL'),
('LAFMSIA', '3794', 'Industrial Products & Services, Main Market', 'LAFARGE MALAYSIA BERHAD', 'LAFARGE MALAYSIA'),
('MISC', '3816', 'Transportation & Logistics, Main Market', 'MISC BHD', 'MISC'),
('MAGNUM', '3859', 'Consumer Products & Services, Main Market', 'MAGNUM BERHAD', 'MAGNUM'),
('MPI', '3867', 'Technology, Main Market', 'MALAYSIAN PACIFIC INDUSTRIES', 'MALAYSIAN PACIFIC'),
('MUDA', '3883', 'Industrial Products & Services, Main Market', 'MUDA HOLDINGS BHD', 'MUDA'),
('MUIIND', '3891', 'Consumer Products & Services, Main Market', 'MALAYAN UNITED INDUSTRIES BHD', 'MALAYAN UNITED'),
('MULPHA', '3905', 'Consumer Products & Services, Main Market', 'MULPHA INTERNATIONAL BHD', 'MULPHA INTERNATIONAL'),
('MUIPROP', '3913', 'Property, Main Market', 'MUI PROPERTIES BHD', 'MUI PROPERTIES'),
('DUTALND', '3948', 'Plantation, Main Market', 'DUTALAND BHD', 'DUTALAND'),
('ORIENT', '4006', 'Consumer Products & Services, Main Market', 'ORIENTAL HOLDINGS BHD', 'ORIENTAL'),
('TADMAX', '4022', 'Property, Main Market', 'TADMAX RESOURCES BERHAD', 'TADMAX'),
('ASIAPAC', '4057', 'Property, Main Market', 'ASIAN PAC HOLDINGS BHD', 'ASIAN PAC'),
('PPB', '4065', 'Consumer Products & Services, Main Market', 'PPB GROUP BHD', 'PPB'),
('PMCORP', '4081', 'Consumer Products & Services, Main Market', 'PAN MALAYSIA CORPORATION BHD', 'PAN MALAYSIA'),
('BAT', '4162', 'Consumer Products & Services, Main Market', 'BRITISH AMERICAN TOBACCO (M)', 'BRITISH AMERICAN TOBACCO (M)'),
('SIME', '4197', 'Consumer Products & Services, Main Market', 'SIME DARBY BHD', 'SIME DARBY'),
('BJLAND', '4219', 'Consumer Products & Services, Main Market', 'BERJAYA LAND BHD', 'BERJAYA LAND'),
('LIONIND', '4235', 'Industrial Products & Services, Main Market', 'LION INDUSTRIES CORPORATION', 'LION'),
('WTK', '4243', 'Industrial Products & Services, Main Market', 'WTK HOLDINGS BHD', 'WTK'),
('IBHD', '4251', 'Property, Main Market', 'I-BHD', 'I-'),
('SEAL', '4286', 'Property, Main Market', 'SEAL INCORPORATED BHD', 'SEAL INCORPORATED'),
('SHCHAN', '4316', 'Plantation, Main Market', 'SIN HENG CHAN (MALAYA) BHD', 'SIN HENG CHAN (MALAYA)'),
('HENGYUAN', '4324', 'Energy, Main Market', 'HENGYUAN REFINING COMPANY BERHAD', 'HENGYUAN REFINING COMPANY'),
('TURIYA', '4359', 'Technology, Main Market', 'TURIYA BHD', 'TURIYA'),
('SMI', '4375', 'Property, Main Market', 'SOUTH MALAYSIA INDUSTRIES BHD', 'SOUTH MALAYSIA'),
('JTIASA', '4383', 'Plantation, Main Market', 'JAYA TIASA HOLDINGS BHD', 'JAYA TIASA'),
('TCHONG', '4405', 'Consumer Products & Services, Main Market', 'TAN CHONG MOTOR HOLDINGS BHD', 'TAN CHONG MOTOR'),
('TASEK', '4448', 'Industrial Products & Services, Main Market', 'TASEK CORPORATION BHD', 'TASEK'),
('TASEK-PA', '4448P', 'Industrial Products & Services - Main Market', NULL, NULL),
('DNEX', '4456', 'Technology, Main Market', 'DAGANG NEXCHANGE BERHAD', 'DAGANG NEXCHANGE'),
('PHB', '4464', 'Property, Main Market', 'PEGASUS HEIGHTS BERHAD', 'PEGASUS HEIGHTS'),
('MEDIA', '4502', 'Telecommunications & Media, Main Market', 'MEDIA PRIMA BHD', 'MEDIA PRIMA'),
('UMW', '4588', 'Consumer Products & Services, Main Market', 'UMW HOLDINGS BHD', 'UMW'),
('SAPRES', '4596', 'Property, Main Market', 'SAPURA RESOURCES BHD', 'SAPURA'),
('POS', '4634', 'Transportation & Logistics, Main Market', 'POS MALAYSIA BHD', 'POS MALAYSIA'),
('YTL', '4677', 'Utilities, Main Market', 'YTL CORPORATION BHD', 'YTL'),
('NESTLE', '4707', 'Consumer Products & Services, Main Market', 'NESTLE (M) BHD', 'NESTLE (M)'),
('GENM', '4715', 'Consumer Products & Services, Main Market', 'GENTING MALAYSIA BERHAD', 'GENTING MALAYSIA'),
('JAKS', '4723', 'Construction, Main Market', 'JAKS RESOURCES BERHAD', 'JAKS'),
('SCIENTX', '4731', 'Industrial Products & Services, Main Market', 'SCIENTEX BERHAD', 'SCIENTEX'),
('ANCOM', '4758', 'Industrial Products & Services, Main Market', 'ANCOM BHD', 'ANCOM'),
('KTB', '4847', 'Consumer Products & Services, Main Market', 'KONSORTIUM TRANSNASIONAL BHD', 'KONSORTIUM TRANSNASIONAL'),
('TM', '4863', 'Telecommunications & Media, Main Market', 'TELEKOM MALAYSIA BHD', 'TELEKOM MALAYSIA'),
('TA', '4898', 'Financial Services, Main Market', 'TA ENTERPRISE BHD', 'TA ENTERPRISE'),
('MALPAC', '4936', 'Plantation, Main Market', 'MALPAC HOLDINGS BHD', 'MALPAC'),
('NYLEX', '4944', 'Industrial Products & Services, Main Market', 'NYLEX (M) BHD', 'NYLEX (M)'),
('AHP', '4952', 'Real Estate Investment Trusts, Main Market', 'AMANAH HARTA TANAH PNB', 'AMANAH HARTA TANAH PNB'),
('VERSATL', '4995', 'Industrial Products & Services, Main Market', 'VERSATILE CREATIVE BHD', 'VERSATILE CREATIVE'),
('HUMEIND', '5000', 'Industrial Products & Services, Main Market', 'HUME INDUSTRIES BHD', 'HUME'),
('MIECO', '5001', 'Industrial Products & Services, Main Market', 'MIECO CHIPBOARD BHD', 'MIECO CHIPBOARD'),
('UNISEM', '5005', 'Technology, Main Market', 'UNISEM (M) BHD', 'UNISEM (M)'),
('MERGE', '5006', 'Construction, Main Market', 'MERGE ENERGY BHD', 'MERGE ENERGY'),
('CHINWEL', '5007', 'Industrial Products & Services, Main Market', 'CHIN WELL HOLDINGS BHD', 'CHIN WELL'),
('HARISON', '5008', 'Consumer Products & Services, Main Market', 'HARRISONS HOLDINGS (M) BHD', 'HARRISONS  (M)'),
('WTHORSE', '5009', 'Industrial Products & Services, Main Market', 'WHITE HORSE BHD', 'WHITE HORSE'),
('TONGHER', '5010', 'Industrial Products & Services, Main Market', 'TONG HERR RESOURCES BHD', 'TONG HERR'),
('MSNIAGA', '5011', 'Technology, Main Market', 'MESINIAGA BHD', 'MESINIAGA'),
('TAANN', '5012', 'Plantation, Main Market', 'TA ANN HOLDINGS BHD', 'TA ANN'),
('AIRPORT', '5014', 'Transportation & Logistics, Main Market', 'MALAYSIA AIRPORTS HOLDINGS BHD', 'MALAYSIA AIRPORTS'),
('APM', '5015', 'Industrial Products & Services, Main Market', 'APM AUTOMOTIVE HOLDINGS BHD', 'APM AUTOMOTIVE'),
('WARISAN', '5016', 'Consumer Products & Services, Main Market', 'WARISAN TC HOLDINGS BHD', 'WARISAN TC'),
('GLOMAC', '5020', 'Property, Main Market', 'GLOMAC BHD', 'GLOMAC'),
('AYS', '5021', 'Industrial Products & Services, Main Market', 'AYS VENTURES BHD', 'AYS VENTURES'),
('PAOS', '5022', 'Consumer Products & Services, Main Market', 'PAOS HOLDINGS BHD', 'PAOS'),
('HUPSENG', '5024', 'Consumer Products & Services, Main Market', 'HUP SENG INDUSTRIES BHD', 'HUP SENG'),
('NWP', '5025', 'Industrial Products & Services, Main Market', 'NWP HOLDINGS BHD', 'NWP'),
('MHC', '5026', 'Plantation, Main Market', 'MHC PLANTATIONS BHD', 'MHC PLANTATIONS'),
('KMLOONG', '5027', 'Plantation, Main Market', 'KIM LOONG RESOURCES BHD', 'KIM LOONG'),
('HTPADU', '5028', 'Technology, Main Market', 'HEITECH PADU BHD', 'HEITECH PADU'),
('FAREAST', '5029', 'Plantation, Main Market', 'FAR EAST HOLDINGS BHD', 'FAR EAST'),
('TIMECOM', '5031', 'Telecommunications & Media, Main Market', 'TIME DOTCOM BHD', 'TIME DOTCOM'),
('BIPORT', '5032', 'Transportation & Logistics, Main Market', 'BINTULU PORT HOLDINGS BHD', 'BINTULU PORT'),
('KNUSFOR', '5035', 'Industrial Products & Services, Main Market', 'KNUSFORD BHD', 'KNUSFORD'),
('EDARAN', '5036', 'Technology, Main Market', 'EDARAN BHD', 'EDARAN'),
('COMPUGT', '5037', 'Industrial Products & Services, Main Market', 'COMPUGATES HOLDINGS BHD', 'COMPUGATES'),
('KSL', '5038', 'Property, Main Market', 'KSL HOLDINGS BHD', 'KSL'),
('MEDAINC', '5040', 'Property, Main Market', NULL, NULL),
('PBA', '5041', 'Utilities, Main Market', 'PBA HOLDINGS BHD', 'PBA'),
('TSRCAP', '5042', 'Construction, Main Market', 'TSR CAPITAL BHD', 'TSR'),
('NPC', '5047', 'Plantation, Main Market', 'NPC RESOURCES BHD', 'NPC'),
('YILAI', '5048', 'Industrial Products & Services, Main Market', 'YI-LAI BHD', 'YI-LAI'),
('CVIEW', '5049', 'Property, Main Market', 'COUNTRY VIEW BHD', 'COUNTRY VIEW'),
('OSK', '5053', 'Property, Main Market', 'OSK HOLDINGS BHD', 'OSK'),
('TRC', '5054', 'Construction, Main Market', 'TRC SYNERGY BHD', 'TRC SYNERGY'),
('ENGTEX', '5056', 'Industrial Products & Services, Main Market', 'ENGTEX GROUP BHD', 'ENGTEX'),
('KINSTEL', '5060', 'Industrial Products & Services, Main Market', 'KINSTEEL BHD', 'KINSTEEL'),
('HUAYANG', '5062', 'Property, Main Market', 'HUA YANG BHD', 'HUA YANG'),
('ORNA', '5065', 'Industrial Products & Services, Main Market', 'ORNAPAPER BHD', 'ORNAPAPER'),
('NTPM', '5066', 'Consumer Products & Services, Main Market', 'NTPM HOLDINGS BHD', 'NTPM'),
('LUSTER', '5068', 'Industrial Products & Services, Main Market', 'LUSTER INDUSTRIES BHD', 'LUSTER'),
('BLDPLNT', '5069', 'Plantation, Main Market', 'BLD PLANTATION BHD', 'BLD PLANTATION'),
('PRTASCO', '5070', 'Construction, Main Market', 'PROTASCO BHD', 'PROTASCO'),
('COASTAL', '5071', 'Energy, Main Market', 'COASTAL CONTRACTS BHD', 'COASTAL CONTRACTS'),
('HIAPTEK', '5072', 'Industrial Products & Services, Main Market', 'HIAP TECK VENTURE BHD', 'HIAP TECK VENTURE'),
('NAIM', '5073', 'Property, Main Market', 'NAIM HOLDINGS BHD', 'NAIM'),
('PLENITU', '5075', 'Property, Main Market', 'PLENITUDE BHD', 'PLENITUDE'),
('MAYBULK', '5077', 'Transportation & Logistics, Main Market', 'MALAYSIAN BULK CARRIERS BHD', 'MALAYSIAN BULK CARRIERS'),
('M&G', '5078', 'Transportation & Logistics, Main Market', NULL, NULL),
('GETS', '5079', 'Consumer Products & Services, Main Market', 'GETS GLOBAL BERHAD', 'GETS GLOBAL'),
('POHKONG', '5080', 'Consumer Products & Services, Main Market', 'POH KONG HOLDINGS BHD', 'POH KONG'),
('EIG', '5081', 'Consumer Products & Services, Main Market', 'ESTHETICS INTERNATIONAL GROUP', 'ESTHETICS INTERNATIONAL'),
('CYMAO', '5082', 'Industrial Products & Services, Main Market', 'CYMAO HOLDINGS BHD', 'CYMAO'),
('IBRACO', '5084', 'Property, Main Market', 'IBRACO BHD', 'IBRACO'),
('MUDAJYA', '5085', 'Construction, Main Market', 'MUDAJAYA GROUP BHD', 'MUDAJAYA'),
('MYCRON', '5087', 'Industrial Products & Services, Main Market', 'MYCRON STEEL BHD', 'MYCRON STEEL'),
('APEX', '5088', 'Financial Services, Main Market', 'APEX EQUITY HOLDINGS BHD', 'APEX EQUITY'),
('MEDIAC', '5090', 'Telecommunications & Media, Main Market', 'MEDIA CHINESE INTERNATIONAL LT', 'MEDIA CHINESE INTERNATIONAL LT'),
('CSCSTEL', '5094', 'Industrial Products & Services, Main Market', 'CSC STEEL HOLDINGS BERHAD', 'CSC STEEL'),
('HEVEA', '5095', 'Industrial Products & Services, Main Market', 'HEVEABOARD BHD', 'HEVEABOARD'),
('MASTEEL', '5098', 'Industrial Products & Services, Main Market', 'MALAYSIA STEEL WORKS (KL)BHD', 'MALAYSIA STEEL WORKS (KL)'),
('AIRASIA', '5099', 'Consumer Products & Services, Main Market', 'AIRASIA GROUP BERHAD', 'AIRASIA'),
('BPPLAS', '5100', 'Industrial Products & Services, Main Market', 'BP PLASTICS HOLDING BHD', 'BP PLASTICS HOLDING'),
('EVERGRN', '5101', 'Industrial Products & Services, Main Market', 'EVERGREEN FIBREBOARD BHD', 'EVERGREEN FIBREBOARD'),
('GCB', '5102', 'Consumer Products & Services, Main Market', 'GUAN CHONG BHD', 'GUAN CHONG'),
('CNI', '5104', 'Consumer Products & Services, Main Market', 'CNI HOLDINGS BHD', 'CNI'),
('CANONE', '5105', 'Industrial Products & Services, Main Market', 'CAN-ONE BHD', 'CAN-ONE'),
('AXREIT', '5106', 'Real Estate Investment Trusts, Main Market', 'AXIS REITS', 'AXIS REITS'),
('IQGROUP', '5107', 'Consumer Products & Services, Main Market', 'IQ GROUP HOLDINGS BHD', 'IQ'),
('ICAP', '5108', 'Closed-End Fund, Main Market', 'ICAPITAL.BIZ BHD', 'I.BIZ'),
('YTLREIT', '5109', 'Real Estate Investment Trusts, Main Market', 'YTL HOSPITALITY REIT', 'YTL HOSPITALITY REIT'),
('UOAREIT', '5110', 'Real Estate Investment Trusts, Main Market', 'UOA REITS', 'UOA REITS'),
('TWRREIT', '5111', 'Real Estate Investment Trusts, Main Market', 'TOWER REITS', 'TOWER REITS'),
('THPLANT', '5112', 'Plantation, Main Market', 'TH PLANTATIONS BHD', 'TH PLANTATIONS'),
('RSAWIT', '5113', 'Plantation, Main Market', 'RIMBUNAN SAWIT BHD', 'RIMBUNAN SAWIT'),
('ALAM', '5115', 'Energy, Main Market', 'ALAM MARITIM RESOURCES BHD', 'ALAM MARITIM'),
('ALAQAR', '5116', 'Real Estate Investment Trusts, Main Market', 'AL-AQAR HEALTHCARE REIT', 'AL-AQAR HEALTHCARE REIT'),
('AMFIRST', '5120', 'Real Estate Investment Trusts, Main Market', 'AMFIRST REITS', 'AMFIRST REITS'),
('HEKTAR', '5121', 'Real Estate Investment Trusts, Main Market', 'HEKTAR REITS', 'HEKTAR REITS'),
('MQREIT', '5123', 'Real Estate Investment Trusts, Main Market', 'MRCB-QUILL REIT', 'MRCB-QUILL REIT'),
('PANTECH', '5125', 'Industrial Products & Services, Main Market', 'PANTECH GROUP HOLDINGS BHD', 'PANTECH'),
('SOP', '5126', 'Plantation, Main Market', 'SARAWAK OIL PALMS BHD', 'SARAWAK OIL PALMS'),
('ARREIT', '5127', 'Real Estate Investment Trusts, Main Market', 'AMANAHRAYA REITS', 'AMANAHRAYA REITS'),
('MELATI', '5129', 'Construction, Main Market', 'MELATI EHSAN HOLDINGS BHD', 'MELATI EHSAN'),
('ATRIUM', '5130', 'Real Estate Investment Trusts, Main Market', 'ATRIUM REITS', 'ATRIUM REITS'),
('ZHULIAN', '5131', 'Consumer Products & Services, Main Market', 'ZHULIAN CORPORATION BHD', 'ZHULIAN'),
('DELEUM', '5132', 'Energy, Main Market', 'DELEUM BHD', 'DELEUM'),
('PENERGY', '5133', 'Energy, Main Market', 'PETRA ENERGY BHD', 'PETRA ENERGY'),
('SAB', '5134', 'Industrial Products & Services, Main Market', 'SOUTHERN ACIDS (M) BHD', 'SOUTHERN ACIDS (M)'),
('SWKPLNT', '5135', 'Plantation, Main Market', 'SARAWAK PLANTATION BHD', 'SARAWAK PLANTATION'),
('COMPLET', '5136', 'Transportation & Logistics, Main Market', 'COMPLETE LOGISTIC SERVICES BHD', 'COMPLETE LOGISTIC SERVICES'),
('HSPLANT', '5138', 'Plantation, Main Market', 'HAP SENG PLANTATIONS HOLDINGS', 'HAP SENG PLANTATIONS'),
('AEONCR', '5139', 'Financial Services, Main Market', 'AEON CREDIT SERVICE (M) BHD', 'AEON CREDIT SERVICE (M)'),
('TASCO', '5140', 'Transportation & Logistics, Main Market', 'TASCO BERHAD', 'TASCO'),
('DAYANG', '5141', 'Energy, Main Market', 'DAYANG ENTERPRISE HOLDINGS BHD', 'DAYANG ENTERPRISE'),
('WASEONG', '5142', 'Energy, Main Market', 'WAH SEONG CORPORATION BHD', 'WAH SEONG'),
('LUXCHEM', '5143', 'Industrial Products & Services, Main Market', 'LUXCHEM CORPORATION BHD', 'LUXCHEM'),
('SEALINK', '5145', 'Transportation & Logistics, Main Market', 'SEALINK INTERNATIONAL BHD', 'SEALINK INTERNATIONAL'),
('SAMCHEM', '5147', 'Industrial Products & Services, Main Market', 'SAMCHEM HOLDINGS BERHAD', 'SAMCHEM'),
('UEMS', '5148', 'Property, Main Market', 'UEM SUNRISE BERHAD', 'UEM SUNRISE'),
('TAS', '5149', 'Transportation & Logistics, Main Market', 'TAS OFFSHORE BERHAD', 'TAS OFFSHORE'),
('MSPORTS', '5150', 'Consumer Products & Services, Main Market', 'MULTI SPORTS HOLDINGS LTD', 'MULTI SPORTS  LTD'),
('HALEX', '5151', 'Industrial Products & Services, Main Market', 'HALEX HOLDINGS BERHAD', 'HALEX'),
('MBL', '5152', 'Industrial Products & Services, Main Market', 'MUAR BAN LEE GROUP BERHAD', 'MUAR BAN LEE'),
('XINQUAN', '5155', 'Consumer Products & Services, Main Market', 'XINGQUAN INT SPORTS HLDG LTD', 'XINGQUAN INT SPORTS HLDG LTD'),
('XDL', '5156', 'Consumer Products & Services, Main Market', 'XIDELANG HOLDINGS LTD', 'XIDELANG  LTD'),
('SAUDEE', '5157', 'Consumer Products & Services, Main Market', 'SAUDEE GROUP BERHAD', 'SAUDEE'),
('TAGB', '5158', 'Property, Main Market', 'TA GLOBAL BHD', 'TA GLOBAL'),
('YOCB', '5159', 'Consumer Products & Services, Main Market', 'YOONG ONN CORPORATION BERHAD', 'YOONG ONN'),
('HOMERIZ', '5160', 'Consumer Products & Services, Main Market', 'HOMERITZ CORPORATION BERHAD', 'HOMERITZ'),
('JCY', '5161', 'Technology, Main Market', 'JCY INTERNATIONAL BERHAD', 'JCY INTERNATIONAL'),
('VSTECS', '5162', 'Technology, Main Market', 'VSTECS BERHAD', 'VSTECS'),
('SEB', '5163', 'Industrial Products & Services, Main Market', 'SEREMBAN ENGINEERING BERHAD', 'SEREMBAN ENGINEERING'),
('HOKHENG', '5165', 'Industrial Products & Services, Main Market', 'HOCK HENG STONE INDUSTRIES BHD', 'HOCK HENG STONE'),
('MINDA', '5166', 'Consumer Products & Services, Main Market', 'MINDA GLOBAL BERHAD', 'MA GLOBAL'),
('TURBO', '5167', 'Industrial Products & Services, Main Market', 'TURBO-MECH BERHAD', 'TURBO-MECH'),
('HARTA', '5168', 'Health Care, Main Market', 'HARTALEGA HOLDINGS BHD', 'HARTALEGA'),
('HOHUP', '5169', 'Construction, Main Market', 'HO HUP CONSTRUCTION COMPANY', 'HO HUP CONSTRUCTION COMPANY'),
('SCABLE', '5170', 'Industrial Products & Services, Main Market', 'SARAWAK CABLE BERHAD', 'SARAWAK CABLE'),
('KIMLUN', '5171', 'Construction, Main Market', 'KIMLUN CORPORATION BERHAD', 'KIMLUN'),
('KSTAR', '5172', 'Consumer Products & Services, Main Market', 'K-STAR SPORTS LIMITED', 'K-STAR SPORTS LIMITED'),
('SYSCORP', '5173', 'Transportation & Logistics, Main Market', 'SHIN YANG SHIPPING CORP BHD', 'SHIN YANG SHIPPING CORP'),
('IVORY', '5175', 'Property, Main Market', 'IVORY PROPERTIES GROUP BERHAD', 'IVORY PROPERTIES'),
('SUNREIT', '5176', 'Real Estate Investment Trusts, Main Market', 'SUNWAY REAL ESTATE INVT TRUST', 'SUNWAY REAL ESTATE INVT TRUST'),
('DYNACIA', '5178', 'Industrial Products & Services, Main Market', 'DYNACIATE GROUP BERHAD', 'DYNACIATE'),
('CMMT', '5180', 'Real Estate Investment Trusts, Main Market', 'CAPITALAND MALAYSIA MALL TRUST', 'AND MALAYSIA MALL TRUST'),
('SIGGAS', '5181', 'Industrial Products & Services, Main Market', 'SIG GASES BERHAD', 'SIG GASES'),
('MCT', '5182', 'Property, Main Market', 'MCT BERHAD', 'MCT'),
('PCHEM', '5183', 'Industrial Products & Services, Main Market', 'PETRONAS CHEMICALS GROUP BHD', 'PETRONAS CHEMICALS'),
('CYPARK', '5184', 'Industrial Products & Services, Main Market', 'CYPARK RESOURCES BERHAD', 'CYPARK'),
('AFFIN', '5185', 'Financial Services, Main Market', 'AFFIN BANK BERHAD', 'AFFIN BANK'),
('MHB', '5186', 'Energy, Main Market', 'MALAYSIA MARINE AND HEAVY ENG', 'MALAYSIA MARINE AND HEAVY ENG'),
('HBGLOB', '5187', 'Consumer Products & Services, Main Market', 'HB GLOBAL LIMITED', 'HB GLOBAL LIMITED'),
('CNOUHUA', '5188', 'Consumer Products & Services, Main Market', 'CHINA OUHUA WINERY HLDGS LTD', 'CHINA OUHUA WINERY HLDGS LTD'),
('MAXWELL', '5189', 'Consumer Products & Services, Main Market', 'MAXWELL INT HOLDINGS BERHAD', 'MAXWELL INT'),
('BENALEC', '5190', 'Construction, Main Market', 'BENALEC HOLDINGS BERHAD', 'BENALEC'),
('TAMBUN', '5191', 'Property, Main Market', 'TAMBUN INDAH LAND BERHAD', 'TAMBUN AH LAND'),
('KSSC', '5192', 'Industrial Products & Services, Main Market', 'K. SENG SENG CORPORATION BHD', 'K. SENG SENG'),
('APFT', '5194', 'Consumer Products & Services, Main Market', 'APFT BERHAD', 'APFT'),
('CENSOF', '5195', 'Technology, Main Market', 'CENSOF HOLDINGS BERHAD', 'CENSOF'),
('BJFOOD', '5196', 'Consumer Products & Services, Main Market', 'BERJAYA FOOD BERHAD', 'BERJAYA FOOD'),
('FLBHD', '5197', 'Industrial Products & Services, Main Market', 'FOCUS LUMBER BERHAD', 'FOCUS LUMBER'),
('AFUJIYA', '5198', 'Industrial Products & Services, Main Market', 'ABM FUJIYA BERHAD', 'ABM FUJIYA'),
('HIBISCS', '5199', 'Energy, Main Market', 'HIBISCUS PETROLEUM BHD', 'HIBISCUS PETROLEUM'),
('UOADEV', '5200', 'Property, Main Market', 'UOA DEVELOPMENT BERHAD', 'UOA DEVELOPMENT'),
('MSM', '5202', 'Consumer Products & Services, Main Market', 'MSM MALAYSIA HOLDINGS BERHAD', 'MSM MALAYSIA'),
('PRESBHD', '5204', 'Technology, Main Market', 'PRESTARIANG BERHAD', 'PRESTARIANG'),
('SENDAI', '5205', 'Construction, Main Market', 'EVERSENDAI CORPORATION BERHAD', 'EVERSENDAI'),
('SBCCORP', '5207', 'Property, Main Market', 'SBC CORPORATION BHD', 'SBC'),
('EITA', '5208', 'Industrial Products & Services, Main Market', 'EITA RESOURCES BERHAD', 'EITA'),
('GASMSIA', '5209', 'Utilities, Main Market', 'GAS MALAYSIA BERHAD', 'GAS MALAYSIA'),
('ARMADA', '5210', 'Energy, Main Market', 'BUMI ARMADA BERHAD', 'BUMI ARMADA'),
('SUNWAY', '5211', 'Industrial Products & Services, Main Market', 'SUNWAY BERHAD', 'SUNWAY'),
('PAVREIT', '5212', 'Real Estate Investment Trusts, Main Market', 'PAVILION REAL ESTATE INV TRUST', 'PAVILION REAL ESTATE INV TRUST'),
('SNTORIA', '5213', 'Property, Main Market', 'SENTORIA GROUP BERHAD', 'SENTORIA'),
('CSL', '5214', 'Consumer Products & Services, Main Market', 'CHINA STATIONERY LIMITED', 'CHINA STATIONERY LIMITED'),
('DSONIC', '5216', 'Technology, Main Market', 'DATASONIC GROUP BERHAD', 'DATASONIC'),
('SAPNRG', '5218', 'Energy, Main Market', 'SAPURA ENERGY BERHAD', 'SAPURA ENERGY'),
('PESTECH', '5219', 'Industrial Products & Services, Main Market', 'PESTECH INTERNATIONAL BERHAD', 'PESTECH INTERNATIONAL'),
('GLOTEC', '5220', 'Industrial Products & Services, Main Market', 'GLOBALTEC FORMATION BERHAD', 'GLOBALTEC FORMATION'),
('FGV', '5222', 'Plantation, Main Market', 'FGV HOLDINGS BERHAD', 'FGV'),
('MENTIGA', '5223', 'Industrial Products & Services, Main Market', 'MENTIGA CORPORATION BHD', 'MENTIGA'),
('IHH', '5225', 'Health Care, Main Market', 'IHH HEALTHCARE BERHAD', 'IHH HEALTHCARE'),
('GBGAQRS', '5226', 'Construction, Main Market', 'GABUNGAN AQRS BERHAD', 'GABUNGAN AQRS'),
('IGBREIT', '5227', 'Real Estate Investment Trusts, Main Market', 'IGB REAL ESTATE INV TRUST', 'IGB REAL ESTATE INV TRUST'),
('ELKDESA', '5228', 'Financial Services, Main Market', 'ELK-DESA RESOURCES BERHAD', 'ELK-DESA'),
('CAP', '5229', 'Industrial Products & Services, Main Market', 'CHINA AUTOMOBILE PARTS HLD LTD', 'CHINA AUTOMOBILE PARTS HLD LTD'),
('TUNEPRO', '5230', 'Financial Services, Main Market', 'TUNE PROTECT GROUP BERHAD', 'TUNE PROTECT'),
('PELIKAN', '5231', 'Consumer Products & Services, Main Market', 'PELIKAN INT.CORPORATION BHD', 'PELIKAN INT.'),
('LEONFB', '5232', 'Industrial Products & Services, Main Market', 'LEON FUAT BERHAD', 'LEON FUAT'),
('KLCC', '5235SS', 'Real Estate Investment Trusts, Main Market', 'KLCC PROP&REITS-STAPLED SEC', 'KLCC PROP&REITS-STAPLED SEC'),
('MATRIX', '5236', 'Property, Main Market', 'MATRIX CONCEPTS HOLDINGS BHD', 'MATRIX CONCEPTS'),
('MPHBCAP', '5237', 'Financial Services, Main Market', 'MPHB Capital Berhad', 'MPHB Capital Berhad'),
('AAX', '5238', 'Consumer Products & Services, Main Market', 'AIRASIA X BERHAD', 'AIRASIA X'),
('TITIJYA', '5239', 'Property, Main Market', 'TITIJAYA LAND BERHAD', 'TITIJAYA LAND'),
('SOLID', '5242', 'Consumer Products & Services, Main Market', 'SOLID AUTOMOTIVE BHD', 'SOLID AUTOMOTIVE'),
('VELESTO', '5243', 'Energy, Main Market', 'VELESTO ENERGY BERHAD', 'VELESTO ENERGY'),
('CARING', '5245', 'Consumer Products & Services, Main Market', 'CARING PHARMACY GROUP BERHAD', 'CARING PHARMACY'),
('WPRTS', '5246', 'Transportation & Logistics, Main Market', 'WESTPORTS HOLDINGS BERHAD', 'WESTPORTS'),
('KAREX', '5247', 'Consumer Products & Services, Main Market', 'KAREX BERHAD', 'KAREX'),
('BAUTO', '5248', 'Consumer Products & Services, Main Market', 'BERMAZ AUTO BERHAD', 'BERMAZ AUTO'),
('IOIPG', '5249', 'Property, Main Market', 'IOI PROPERTIES GROUP BERHAD', 'IOI PROPERTIES'),
('SEM', '5250', 'Consumer Products & Services, Main Market', '7-ELEVEN MALAYSIA HOLDINGS BERHAD', '7-ELEVEN MALAYSIA'),
('SASBADI', '5252', 'Telecommunications & Media, Main Market', 'SASBADI HOLDINGS BHD', 'SASBADI'),
('ECONBHD', '5253', 'Construction, Main Market', 'ECONPILE HOLDINGS BHD', 'ECONPILE'),
('BPLANT', '5254', 'Plantation, Main Market', 'BOUSTEAD PLANTATIONS BHD', 'BOUSTEAD PLANTATIONS'),
('ICON', '5255', 'Energy, Main Market', 'ICON OFFSHORE BERHAD', 'ICON OFFSHORE'),
('REACH', '5256', 'Energy, Main Market', 'REACH ENERGY BHD', 'REACH ENERGY'),
('CARIMIN', '5257', 'Energy, Main Market', 'CARIMIN PETROLEUM BERHAD', 'CARIMIN PETROLEUM'),
('BIMB', '5258', 'Financial Services, Main Market', 'BIMB HOLDINGS BHD', 'BIMB'),
('EATECH', '5259', 'Transportation & Logistics, Main Market', 'E.A.TECHNIQUE (M) BERHAD', 'E.A.TECHNIQUE (M)'),
('OWG', '5260', 'Consumer Products & Services, Main Market', 'ONLY WORLD GROUP HOLDINGS BERHAD', 'ONLY WORLD'),
('SUNCON', '5263', 'Construction, Main Market', 'SUNWAY CONSTRUCTION GROUP BERHAD', 'SUNWAY CONSTRUCTION'),
('MALAKOF', '5264', 'Utilities, Main Market', 'MALAKOFF CORPORATION BERHAD', 'MALAKOFF'),
('DOLPHIN', '5265', 'Industrial Products & Services, Main Market', 'DOLPHIN INTERNATIONAL BERHAD', 'DOLPHIN INTERNATIONAL'),
('XINHWA', '5267', 'Transportation & Logistics, Main Market', 'XIN HWA HOLDINGS BERHAD', 'XIN HWA'),
('IKHMAS', '5268', 'Construction, Main Market', 'IKHMAS JAYA GROUP BERHAD', 'IKHMAS JAYA'),
('ALSREIT', '5269', 'Real Estate Investment Trusts, Main Market', 'AL-SALAM REAL ESTATE INVESTMENT TRUST', 'AL-SALAM REAL ESTATE INVESTMENT TRUST'),
('RSENA', '5270', 'SPAC, Main Market', 'RED SENA BERHAD', 'RED SENA'),
('PECCA', '5271', 'Industrial Products & Services, Main Market', 'PECCA GROUP BERHAD', 'PECCA'),
('RANHILL', '5272', 'Utilities, Main Market', 'RANHILL HOLDINGS BERHAD', 'RANHILL'),
('CHINHIN', '5273', 'Industrial Products & Services, Main Market', 'CHIN HIN GROUP BERHAD', 'CHIN HIN'),
('HLCAP', '5274', 'Financial Services, Main Market', 'HONG LEONG CAPITAL BERHAD', 'HONG LEONG'),
('MYNEWS', '5275', 'Consumer Products & Services, Main Market', 'MYNEWS HOLDINGS BERHAD', 'MYNEWS'),
('DANCO', '5276', 'Industrial Products & Services, Main Market', 'DANCOMECH HOLDINGS BERHAD', 'DANCOMECH'),
('FPGROUP', '5277', 'Industrial Products & Services, Main Market', 'FOUNDPAC GROUP BERHAD', 'FOUNDPAC'),
('RHONEMA', '5278', 'Consumer Products & Services, Main Market', 'RHONE MA HOLDINGS BERHAD', 'RHONE MA'),
('SERBADK', '5279', 'Energy, Main Market', 'SERBA DINAMIK HOLDINGS BERHAD', 'SERBA DINAMIK'),
('KIPREIT', '5280', 'Real Estate Investment Trusts, Main Market', 'KIP REAL ESTATE INVESTMENT TRUST', 'KIP REAL ESTATE INVESTMENT TRUST'),
('ADVCON', '5281', 'Construction, Main Market', 'ADVANCECON HOLDINGS BERHAD', 'ADVANCECON'),
('EWINT', '5283', 'Property, Main Market', 'ECO WORLD INTERNATIONAL BERHAD', 'ECO WORLD INTERNATIONAL'),
('LCTITAN', '5284', 'Industrial Products & Services, Main Market', 'LOTTE CHEMICAL TITAN HOLDING BERHAD', 'LOTTE CHEMICAL TITAN HOLDING'),
('SIMEPLT', '5285', 'Plantation, Main Market', 'SIME DARBY PLANTATION BERHAD', 'SIME DARBY PLANTATION'),
('MI', '5286', 'Technology, Main Market', 'MI TECHNOVATION BERHAD', 'MI TECHNOVATION'),
('SIMEPROP', '5288', 'Property, Main Market', 'SIME DARBY PROPERTY BERHAD', 'SIME DARBY PROPERTY'),
('TECHBND', '5289', 'Industrial Products & Services - Main Market', 'TECHBOND GROUP BERHAD', 'TECHBOND'),
('TENAGA', '5347', 'Utilities, Main Market', 'TENAGA NASIONAL BHD', 'TENAGA NASIONAL'),
('DAIMAN', '5355', 'Property, Main Market', 'DAIMAN DEVELOPMENT BHD', 'DAIMAN DEVELOPMENT'),
('KIMHIN', '5371', 'Industrial Products & Services, Main Market', 'KIM HIN INDUSTRY BHD', 'KIM HIN USTRY'),
('GAMUDA', '5398', 'Construction, Main Market', 'GAMUDA BHD', 'GAMUDA'),
('TROP', '5401', 'Property, Main Market', 'TROPICANA CORPORATION BERHAD', 'TROPICANA'),
('PERSTIM', '5436', 'Industrial Products & Services, Main Market', 'PSAHAAN SADUR TIMAH MSIA', 'PSAHAAN SADUR TIMAH MSIA'),
('SHANG', '5517', 'Consumer Products & Services, Main Market', 'SHANGRI-LA HOTELS (M) BHD', 'SHANGRI-LA HOTELS (M)'),
('OCB', '5533', 'Consumer Products & Services, Main Market', 'OCB BHD', 'OCB'),
('APB', '5568', 'Industrial Products & Services, Main Market', 'APB RESOURCES BHD', 'APB'),
('MINHO', '5576', 'Industrial Products & Services, Main Market', 'MINHO (M) BHD', 'MINHO (M)'),
('YEELEE', '5584', 'Consumer Products & Services, Main Market', 'YEE LEE CORPORATION BHD', 'YEE LEE'),
('GCE', '5592', 'Consumer Products & Services, Main Market', 'GRAND CENTRAL ENTERPRISES BHD', 'GRAND CENTRAL ENTERPRISES'),
('IGBB', '5606', 'Property, Main Market', 'IGB BERHAD', 'IGB'),
('ILB', '5614', 'Transportation & Logistics, Main Market', 'INTEGRATED LOGISTICS BHD', 'INTEGRATED'),
('PEB', '5622', 'Construction, Main Market', 'PIMPINAN EHSAN BERHAD', 'PIMPINAN EHSAN'),
('GPHAROS', '5649', 'Industrial Products & Services, Main Market', 'GOLDEN PHAROS BHD', 'GOLDEN PHAROS'),
('PARKSON', '5657', 'Consumer Products & Services, Main Market', 'PARKSON HOLDINGS BHD', 'PARKSON'),
('SSTEEL', '5665', 'Industrial Products & Services, Main Market', 'SOUTHERN STEEL BHD', 'SOUTHERN STEEL'),
('IPMUDA', '5673', 'Industrial Products & Services, Main Market', 'IPMUDA BHD', 'IPMUDA'),
('PETDAG', '5681', 'Consumer Products & Services, Main Market', 'PETRONAS DAGANGAN BHD', 'PETRONAS DAGANGAN'),
('MUHIBAH', '5703', 'Construction, Main Market', 'MUHIBBAH ENGINEERING (M) BHD', 'MUHIBBAH ENGINEERING (M)'),
('CHHB', '5738', 'Property, Main Market', 'COUNTRY HEIGHTS HOLDINGS BHD', 'COUNTRY HEIGHTS'),
('UTUSAN', '5754', 'Telecommunications & Media, Main Market', 'UTUSAN MELAYU (M) BHD', 'UTUSAN MELAYU (M)'),
('LBS', '5789', 'Property, Main Market', 'LBS BINA GROUP BHD', 'LBS BINA'),
('CHOOBEE', '5797', 'Industrial Products & Services, Main Market', 'CHOO BEE METAL INDUSTRIES BHD', 'CHOO BEE METAL'),
('HLBANK', '5819', 'Financial Services, Main Market', 'HONG LEONG BANK BHD', 'HONG LEONG BANK'),
('OIB', '5827', 'Property, Main Market', 'ORIENTAL INTEREST BHD', 'ORIENTAL INTEREST'),
('DOLMITE', '5835', 'Industrial Products & Services, Main Market', 'DOLOMITE CORPORATION BHD', 'DOLOMITE'),
('KPS', '5843', 'Utilities, Main Market', 'KUMPULAN PERANGSANG SELANGOR', 'KUMPULAN PERANGSANG SELANGOR'),
('KPJ', '5878', 'Health Care, Main Market', 'KPJ HEALTHCARE BHD', 'KPJ HEALTHCARE'),
('MBG', '5886', 'Consumer Products & Services, Main Market', 'MINTYE BERHAD', 'MINTYE'),
('DKSH', '5908', 'Consumer Products & Services, Main Market', 'DKSH HOLDINGS(M)BHD', 'DKSH (M)'),
('MSC', '5916', 'Industrial Products & Services, Main Market', 'MALAYSIA SMELTING CORPORATION', 'MALAYSIA SMELTING'),
('MTDACPI', '5924', 'Construction, Main Market', 'MTD ACPI ENGINEERING BHD', 'MTD ACPI ENGINEERING'),
('BPURI', '5932', 'Construction, Main Market', 'BINA PURI HOLDINGS BHD', 'BINA PURI'),
('AMVERTON', '5959', 'Property, Main Market', 'AMVERTON BERHAD', 'AMVERTON'),
('MBMR', '5983', 'Consumer Products & Services, Main Market', 'MBM RESOURCES BHD', 'MBM'),
('P&O', '6009', 'Financial Services, Main Market', NULL, NULL),
('MAXIS', '6012', 'Telecommunications & Media, Main Market', 'MAXIS BERHAD', 'MAXIS'),
('SHL', '6017', 'Property, Main Market', 'SHL CONSOLIDATED BHD', 'SHL CONSOLIDATED'),
('BJMEDIA', '6025', 'Telecommunications & Media, Main Market', 'BERJAYA MEDIA BHD', 'BERJAYA MEDIA'),
('PETGAS', '6033', 'Utilities, Main Market', 'PETRONAS GAS BHD', 'PETRONAS GAS'),
('FARLIM', '6041', 'Property, Main Market', 'FARLIM GROUP (M) BHD', 'FARLIM  (M)'),
('PCCS', '6068', 'Consumer Products & Services, Main Market', 'PCCS GROUP BHD', 'PCCS'),
('ENCORP', '6076', 'Property, Main Market', 'ENCORP BHD', 'ENCORP'),
('STAR', '6084', 'Telecommunications & Media, Main Market', 'STAR MEDIA GROUP BERHAD', 'STAR MEDIA'),
('MKH', '6114', 'Property, Main Market', 'MKH BERHAD', 'MKH'),
('TAKAFUL', '6139', 'Financial Services, Main Market', 'SYARIKAT TAKAFUL MALAYSIA KELUARGA BERHAD', 'SYARIKAT TAKAFUL MALAYSIA KELUARGA'),
('METROD', '6149', 'Industrial Products & Services, Main Market', 'METROD HOLDINGS BERHAD', 'METROD'),
('BDB', '6173', 'Property, Main Market', 'BINA DARULAMAN BHD', 'BINA DARULAMAN'),
('MALTON', '6181', 'Property, Main Market', 'MALTON BHD', 'MALTON'),
('KHEESAN', '6203', 'Consumer Products & Services, Main Market', 'KHEE SAN BHD', 'KHEE SAN'),
('KIALIM', '6211', 'Industrial Products & Services, Main Market', 'KIA LIM BHD', 'KIA LIM'),
('HSL', '6238', 'Construction, Main Market', 'HOCK SENG LEE BHD', 'HOCK SENG LEE'),
('PDZ', '6254', 'Transportation & Logistics, Main Market', 'PDZ HOLDINGS BHD', 'PDZ'),
('INNO', '6262', 'Plantation, Main Market', 'INNOPRISE PLANTATIONS BERHAD', 'INNOPRISE PLANTATIONS'),
('BOXPAK', '6297', 'Industrial Products & Services, Main Market', 'BOX-PAK (MALAYSIA) BHD', 'BOX-PAK (MALAYSIA)'),
('AMWAY', '6351', 'Consumer Products & Services, Main Market', 'AMWAY (M) HOLDINGS BHD', 'AMWAY (M)'),
('WMG', '6378', 'Property, Main Market', 'WMG HOLDINGS BERHAD', 'WMG'),
('ASTRO', '6399', 'Telecommunications & Media, Main Market', 'ASTRO MALAYSIA HOLDINGS BERHAD', 'ASTRO MALAYSIA'),
('APOLLO', '6432', 'Consumer Products & Services, Main Market', 'APOLLO FOOD HOLDINGS BHD', 'APOLLO FOOD'),
('MNRB', '6459', 'Financial Services, Main Market', 'MNRB HOLDINGS BHD', 'MNRB'),
('KENANGA', '6483', 'Financial Services, Main Market', 'KENANGA INVESTMENT BANK BERHAD', 'KENANGA INVESTMENT BANK'),
('KFIMA', '6491', 'Industrial Products & Services, Main Market', 'KUMPULAN FIMA BHD', 'KUMPULAN FIMA'),
('SURIA', '6521', 'Transportation & Logistics, Main Market', 'SURIA CAPITAL HOLDINGS BHD', 'SURIA'),
('MPCORP', '6548', 'Property, Main Market', 'MALAYSIA PACIFIC CORP BHD', 'MALAYSIA PACIFIC CORP'),
('ANNJOO', '6556', 'Industrial Products & Services, Main Market', 'ANN JOO RESOURCES BHD', 'ANN JOO'),
('KWANTAS', '6572', 'Plantation, Main Market', 'KWANTAS CORPORATION BHD', 'KWANTAS'),
('AEON', '6599', 'Consumer Products & Services, Main Market', 'AEON CO. (M) BHD', 'AEON CO. (M)'),
('BCB', '6602', 'Property, Main Market', 'BCB BHD', 'BCB'),
('PNEPCB', '6637', 'Industrial Products & Services, Main Market', 'PNE PCB BHD', 'PNE PCB'),
('LITRAK', '6645', 'Transportation & Logistics, Main Market', 'LINGKARAN TRANS KOTA HOLDINGS', 'LINGKARAN TRANS KOTA'),
('CRESNDO', '6718', 'Property, Main Market', 'CRESCENDO CORPORATION BHD', 'CRESCENDO'),
('YTLPOWR', '6742', 'Utilities, Main Market', 'YTL POWER INTERNATIONAL BHD', 'YTL POWER INTERNATIONAL'),
('JKGLAND', '6769', 'Property, Main Market', 'JKG LAND BERHAD', 'JKG LAND'),
('PUNCAK', '6807', 'Construction, Main Market', 'PUNCAK NIAGA HOLDINGS BHD', 'PUNCAK NIAGA'),
('EUPE', '6815', 'Property, Main Market', 'EUPE CORPORATION BHD', 'EUPE'),
('KUB', '6874', 'Industrial Products & Services, Main Market', 'KUB MALAYSIA BHD', 'KUB MALAYSIA'),
('AXIATA', '6888', 'Telecommunications & Media, Main Market', 'AXIATA GROUP BERHAD', 'AXIATA'),
('SUBUR', '6904', 'Industrial Products & Services, Main Market', 'SUBUR TIASA HOLDINGS BHD', 'SUBUR TIASA'),
('PASDEC', '6912', 'Property, Main Market', 'PASDEC HOLDINGS BHD', 'PASDEC'),
('FIAMMA', '6939', 'Consumer Products & Services, Main Market', 'FIAMMA HOLDINGS BHD', 'FIAMMA'),
('DIGI', '6947', 'Telecommunications & Media, Main Market', 'DIGI.COM BHD', 'DIGI.COM'),
('VS', '6963', 'Industrial Products & Services, Main Market', 'V.S INDUSTRY BHD', 'V.S USTRY'),
('KOBAY', '6971', 'Industrial Products & Services, Main Market', 'KOBAY TECHNOLOGY BHD', 'KOBAY TECHNOLOGY'),
('BINTAI', '6998', 'Industrial Products & Services, Main Market', 'BINTAI KINDEN CORPORATION BHD', 'BINTAI KEN'),
('Y&G', '7003', 'Property, Main Market', NULL, NULL),
('MCEHLDG', '7004', 'Industrial Products & Services, Main Market', 'MCE HOLDINGS BERHAD', 'MCE'),
('BIG', '7005', 'Industrial Products & Services, Main Market', 'B.I.G. INDUSTRIES BHD', 'B.I.G.'),
('LATITUD', '7006', 'Consumer Products & Services, Main Market', 'LATITUDE TREE HOLDINGS BHD', 'LATITUDE TREE'),
('ARK', '7007', 'Property, Main Market', 'ARK RESOURCES HOLDINGS BERHAD', 'ARK'),
('HOOVER', '7010', 'Property, Main Market', 'GRAND HOOVER BHD', 'GRAND HOOVER'),
('HUBLINE', '7013', 'Transportation & Logistics, Main Market', 'HUBLINE BHD', 'HUBLINE'),
('YLI', '7014', 'Industrial Products & Services, Main Market', 'YLI HOLDINGS BHD', 'YLI'),
('CHUAN', '7016', 'Industrial Products & Services, Main Market', 'CHUAN HUAT RESOURCES BHD', 'CHUAN HUAT'),
('KOMARK', '7017', 'Industrial Products & Services, Main Market', 'KOMARKCORP BHD', 'KOMARKCORP'),
('CME', '7018', 'Industrial Products & Services, Main Market', 'CME GROUP BHD', 'CME'),
('YKGI', '7020', 'Industrial Products & Services, Main Market', 'YKGI HOLDINGS BERHAD', 'YKGI'),
('GTRONIC', '7022', 'Technology, Main Market', 'GLOBETRONICS TECHNOLOGY BHD', 'GLOBETRONICS TECHNOLOGY'),
('WOODLAN', '7025', 'Industrial Products & Services, Main Market', 'WOODLANDOR HOLDINGS BHD', 'WOODLANDOR'),
('ZECON', '7028', 'Construction, Main Market', 'ZECON BHD', 'ZECON'),
('MASTER', '7029', 'Industrial Products & Services, Main Market', 'MASTER-PACK GROUP BERHAD', 'MASTER-PACK'),
('AMTEL', '7031', 'Telecommunications & Media, Main Market', 'AMTEL HOLDINGS BHD', 'AMTEL'),
('HIGHTEC', '7033', 'Industrial Products & Services, Main Market', 'KUMPULAN H&L HIGH-TECH BHD', 'KUMPULAN H&L HIGH-TECH'),
('TGUAN', '7034', 'Industrial Products & Services, Main Market', 'THONG GUAN INDUSTRIES BHD', 'THONG GUAN'),
('CCK', '7035', 'Consumer Products & Services, Main Market', 'CCK CONSOLIDATED HOLDINGS BHD', 'CCK CONSOLIDATED'),
('BORNOIL', '7036', 'Industrial Products & Services, Main Market', 'BORNEO OIL BHD', 'BORNEO OIL'),
('JMR', '7043', 'Industrial Products & Services, Main Market', 'JMR CONGLOMERATION BHD', 'JMR CONGLOMERATION'),
('SCOMIES', '7045', 'Energy, Main Market', 'SCOMI ENERGY SERVICES BHD', 'SCOMI ENERGY SERVICES'),
('FAJAR', '7047', 'Construction, Main Market', 'FAJARBARU BUILDER GRP BHD', 'FAJARBARU BUILDER GRP'),
('ATLAN', '7048', 'Consumer Products & Services, Main Market', 'ATLAN HOLDINGS BHD', 'ATLAN'),
('WONG', '7050', 'Industrial Products & Services, Main Market', 'WONG ENGINEERING CORPORATION', 'WONG ENGINEERING'),
('AMTEK', '7051', 'Consumer Products & Services, Main Market', 'AMTEK HOLDINGS BHD', 'AMTEK'),
('PADINI', '7052', 'Consumer Products & Services, Main Market', 'PADINI HOLDINGS BHD', 'PADINI');
INSERT INTO `main_listed_companies` (`stock_name`, `stock_code`, `business_area`, `company_name`, `known_name`) VALUES
('SEEHUP', '7053', 'Transportation & Logistics, Main Market', 'SEE HUP CONSOLIDATED BHD', 'SEE HUP CONSOLIDATED'),
('AASIA', '7054', 'Plantation, Main Market', 'ASTRAL ASIA BHD', 'ASTRAL ASIA'),
('PLB', '7055', 'Property, Main Market', 'PLB ENGINEERING BHD', 'PLB ENGINEERING'),
('NHFATT', '7060', 'Consumer Products & Services, Main Market', 'NEW HOONG FATT HOLDINGS BHD', 'NEW HOONG FATT'),
('KHIND', '7062', 'Consumer Products & Services, Main Market', 'KHIND HOLDINGS BHD', 'KH'),
('YONGTAI', '7066', 'Property, Main Market', 'YONG TAI BHD', 'YONG TAI'),
('VIZIONE', '7070', 'Construction, Main Market', 'VIZIONE HOLDINGS BERHAD', 'VIZIONE'),
('OCR', '7071', 'Construction, Main Market', 'OCR GROUP BERHAD', 'OCR'),
('SEACERA', '7073', 'Industrial Products & Services, Main Market', 'SEACERA GROUP BERHAD', 'SEACERA'),
('CBIP', '7076', 'Industrial Products & Services, Main Market', 'CB INDUSTRIAL PRODUCT HOLDING', 'CB USTRIAL PRODUCT HOLDING'),
('GSB', '7077', 'Property, Main Market', 'GSB GROUP BHD', 'GSB'),
('AZRB', '7078', 'Construction, Main Market', 'AHMAD ZAKI RESOURCES BHD', 'AHMAD ZAKI'),
('TIGER', '7079', 'Property, Main Market', 'TIGER SYNERGY BERHAD', 'TIGER SYNERGY'),
('PERMAJU', '7080', 'Consumer Products & Services, Main Market', 'PERMAJU INDUSTRIES BHD', 'PERMAJU'),
('PHARMA', '7081', 'Health Care, Main Market', 'PHARMANIAGA BHD', 'PHARMANIAGA'),
('SYF', '7082', 'Consumer Products & Services, Main Market', 'SYF RESOURCES BHD', 'SYF'),
('ANALABS', '7083', 'Industrial Products & Services, Main Market', 'ANALABS RESOURCES BHD', 'ANALABS'),
('QL', '7084', 'Consumer Products & Services, Main Market', 'QL RESOURCES BHD', 'QL'),
('LTKM', '7085', 'Consumer Products & Services, Main Market', 'LTKM BHD', 'LTKM'),
('ABLEGRP', '7086', 'Industrial Products & Services, Main Market', 'ABLEGROUP BERHAD', 'ABLE'),
('MAGNI', '7087', 'Consumer Products & Services, Main Market', 'MAGNI-TECH INDUSTRIES BHD', 'MAGNI-TECH'),
('POHUA', '7088', 'Consumer Products & Services, Main Market', NULL, NULL),
('LIIHEN', '7089', 'Consumer Products & Services, Main Market', 'LII HEN INDUSTRIES BHD', 'LII HEN'),
('AHEALTH', '7090', 'Health Care, Main Market', 'APEX HEALTHCARE BHD', 'APEX HEALTHCARE'),
('UNIMECH', '7091', 'Industrial Products & Services, Main Market', 'UNIMECH GROUP BHD', 'UNIMECH'),
('EUROSP', '7094', 'Consumer Products & Services, Main Market', 'EUROSPAN HOLDINGS BHD', 'EUROSPAN'),
('PIE', '7095', 'Industrial Products & Services, Main Market', 'P.I.E. INDUSTRIAL BHD', 'P.I.E. USTRIAL'),
('GPA', '7096', 'Industrial Products & Services, Main Market', 'GPA HOLDINGS BHD', 'GPA'),
('TAWIN', '7097', 'Industrial Products & Services, Main Market', 'TA WIN HOLDINGS BHD', 'TA WIN'),
('ATTA', '7099', 'Industrial Products & Services, Main Market', 'ATTA GLOBAL GROUP BERHAD', 'ATTA GLOBAL'),
('UCHITEC', '7100', 'Industrial Products & Services, Main Market', 'UCHI TECHNOLOGIES BHD', 'UCHI TECHNOLOGIES'),
('SPRITZER', '7103', 'Consumer Products & Services, Main Market', 'SPRITZER BHD', 'SPRITZER'),
('HCK', '7105', 'Property, Main Market', 'HCK CAPITAL GROUP BERHAD', 'HCK'),
('SUPERMX', '7106', 'Health Care, Main Market', 'SUPERMAX CORPORATION BHD', 'SUPERMAX'),
('OFI', '7107', 'Consumer Products & Services, Main Market', 'ORIENTAL FOOD INDUSTRIES HLDG', 'ORIENTAL FOOD  HLDG'),
('PERDANA', '7108', 'Energy, Main Market', 'PERDANA PETROLEUM BERHAD', 'PERDANA PETROLEUM'),
('TOPGLOV', '7113', 'Health Care, Main Market', 'TOP GLOVE CORPORATION BHD', 'TOP GLOVE'),
('DNONCE', '7114', 'Industrial Products & Services, Main Market', 'DNONCE TECHNOLOGY BHD', 'DNONCE TECHNOLOGY'),
('SKBSHUT', '7115', 'Industrial Products & Services, Main Market', 'SKB SHUTTERS CORPORATION BHD', 'SKB SHUTTERS'),
('CJCEN', '7117', 'Transportation & Logistics, Main Market', 'CJ CENTURY LOGISTICS HOLDINGS BERHAD', 'CJ CENTURY'),
('DEGEM', '7119', 'Consumer Products & Services, Main Market', 'DEGEM BHD', 'DEGEM'),
('ACOSTEC', '7120', 'Consumer Products & Services, Main Market', 'ACOUSTECH BHD', 'ACOUSTECH'),
('XIANLNG', '7121', 'Consumer Products & Services, Main Market', 'XIAN LENG HOLDINGS BHD', 'XIAN LENG'),
('YFG', '7122', 'Industrial Products & Services, Main Market', 'YFG BERHAD', 'YFG'),
('PWORTH', '7123', 'Industrial Products & Services, Main Market', 'PRICEWORTH INTERNATIONAL BHD', 'PRICEWORTH INTERNATIONAL'),
('LONBISC', '7126', 'Consumer Products & Services, Main Market', 'LONDON BISCUITS BHD', 'LONDON BISCUITS'),
('CAMRES', '7128', 'Consumer Products & Services, Main Market', 'CAM RESOURCES BHD', 'CAM'),
('ASIAFLE', '7129', 'Consumer Products & Services, Main Market', 'ASIA FILE CORPORATION BHD', 'ASIA FILE'),
('KPOWER', '7130', 'Consumer Products & Services, Main Market', 'KUMPULAN POWERNET BHD', 'KUMPULAN POWERNET'),
('ACME', '7131', 'Property, Main Market', 'ACME HOLDINGS BERHAD', 'ACME'),
('SMISCOR', '7132', 'Industrial Products & Services, Main Market', 'SMIS CORPORATION BHD', 'SMIS'),
('ULICORP', '7133', 'Industrial Products & Services, Main Market', 'UNITED U-LI CORPORATION BHD', 'UNITED U-LI'),
('PWF', '7134', 'Consumer Products & Services, Main Market', 'PWF CONSOLIDATED BERHAD', 'PWF CONSOLIDATED'),
('UMS', '7137', 'Industrial Products & Services, Main Market', 'UMS HOLDINGS BHD', 'UMS'),
('NICE', '7139', 'Consumer Products & Services, Main Market', 'NICHE CAPITAL EMAS HLDG BHD', 'NICHE  EMAS HLDG'),
('OKA', '7140', 'Industrial Products & Services, Main Market', 'OKA CORPORATION BHD', 'OKA'),
('STONE', '7143', 'Industrial Products & Services, Main Market', 'STONE MASTER CORPORATION BHD', 'STONE MASTER'),
('PSIPTEK', '7145', 'Construction, Main Market', 'PRINSIPTEK CORPORATION BHD', 'PRINSIPTEK'),
('AEM', '7146', 'Industrial Products & Services, Main Market', 'AE MULTI HOLDINGS BHD', 'AE MULTI'),
('DPHARMA', '7148', 'Health Care, Main Market', 'DUOPHARMA BIOTECH BERHAD', 'DUOPHARMA BIOTECH'),
('ENGKAH', '7149', 'Consumer Products & Services, Main Market', 'ENG KAH CORPORATION BHD', 'ENG KAH'),
('JAYCORP', '7152', 'Consumer Products & Services, Main Market', 'JAYCORP BHD', 'JAYCORP'),
('KOSSAN', '7153', 'Health Care, Main Market', 'KOSSAN RUBBER INDUSTRIES BHD', 'KOSSAN RUBBER'),
('CAELY', '7154', 'Consumer Products & Services, Main Market', 'CAELY HOLDINGS BHD', 'CAELY'),
('SKPRES', '7155', 'Industrial Products & Services, Main Market', 'SKP RESOURCES BHD', 'SKP'),
('CYL', '7157', 'Industrial Products & Services, Main Market', 'CYL CORPORATION BHD', 'CYL'),
('SCOMI', '7158', 'Energy, Main Market', 'SCOMI GROUP BHD', 'SCOMI'),
('PENTA', '7160', 'Technology, Main Market', 'PENTAMASTER CORPORATION BHD', 'PENTAMASTER'),
('KERJAYA', '7161', 'Construction, Main Market', 'KERJAYA PROSPEK GROUP BERHAD', 'KERJAYA PROSPEK'),
('ASTINO', '7162', 'Industrial Products & Services, Main Market', 'ASTINO BHD', 'ASTINO'),
('PJBUMI', '7163', 'Industrial Products & Services, Main Market', 'PJBUMI BHD', 'PJBUMI'),
('KNM', '7164', 'Energy, Main Market', 'KNM GROUP BHD', 'KNM'),
('DWL', '7165', 'Industrial Products & Services, Main Market', 'DWL RESOURCES BERHAD', 'DWL'),
('JOHOTIN', '7167', 'Consumer Products & Services, Main Market', 'JOHORE TIN BHD', 'JOHORE TIN'),
('PRG', '7168', 'Consumer Products & Services, Main Market', 'PRG HOLDINGS BERHAD', 'PRG'),
('DOMINAN', '7169', 'Industrial Products & Services, Main Market', 'DOMINANT ENTERPRISE BHD', 'DOMINANT ENTERPRISE'),
('LFECORP', '7170', 'Industrial Products & Services, Main Market', 'LFE CORPORATION BHD', 'LFE'),
('PMBTECH', '7172', 'Industrial Products & Services, Main Market', 'PMB TECHNOLOGY BHD', 'PMB TECHNOLOGY'),
('TOYOINK', '7173', 'Industrial Products & Services, Main Market', 'TOYO INK GROUP BHD', 'TOYO INK'),
('CAB', '7174', 'Consumer Products & Services, Main Market', 'CAB CAKARAN CORPORATION BHD', 'CAB CAKARAN'),
('TPC', '7176', 'Consumer Products & Services, Main Market', 'TPC PLUS BHD', 'TPC PLUS'),
('YSPSAH', '7178', 'Health Care, Main Market', 'Y.S.P.SOUTHEAST ASIA HOLDING', 'Y.S.P.SOUTHEAST ASIA HOLDING'),
('DBE', '7179', 'Consumer Products & Services, Main Market', 'D.B.E. GURNEY RESOURCES BHD', 'D.B.E. GURNEY'),
('SERNKOU', '7180', 'Consumer Products & Services, Main Market', 'SERN KOU RESOURCES BHD', 'SERN KOU'),
('ATURMJU', '7181', 'Industrial Products & Services, Main Market', 'ATURMAJU RESOURCES BHD', 'ATURMAJU'),
('EKA', '7182', 'Consumer Products & Services, Main Market', 'EKA NOODLES BERHAD', 'EKA NOODLES'),
('IRETEX', '7183', 'Industrial Products & Services, Main Market', 'IRE-TEX CORPORATION BHD', 'IRE-TEX'),
('G3', '7184', 'Consumer Products & Services, Main Market', 'G3 GLOBAL BERHAD', 'G3 GLOBAL'),
('SWSCAP', '7186', 'Consumer Products & Services, Main Market', 'SWS CAPITAL BERHAD', 'SWS'),
('CHGP', '7187', 'Transportation & Logistics, Main Market', 'CHIN HIN GROUP PROPERTY BERHAD', 'CHIN HIN  PROPERTY'),
('BTM', '7188', 'Industrial Products & Services, Main Market', 'BTM RESOURCES BHD', 'BTM'),
('MBWORLD', '7189', 'Property, Main Market', 'MB WORLD GROUP BERHAD', 'MB WORLD'),
('PPG', '7190', 'Telecommunications & Media, Main Market', 'PELANGI PUBLISHING GROUP BHD', 'PELANGI PUBLISHING'),
('ADVENTA', '7191', 'Health Care, Main Market', 'ADVENTA BHD', 'ADVENTA'),
('GOODWAY', '7192', 'Industrial Products & Services, Main Market', 'GOODWAY INTEGRATED INDUSTRIES', 'GOODWAY INTEGRATED'),
('COMCORP', '7195', 'Industrial Products & Services, Main Market', 'COMINTEL CORPORATION BHD', 'COMINTEL'),
('GESHEN', '7197', 'Industrial Products & Services, Main Market', 'GE-SHEN CORPORATION BHD', 'GE-SHEN'),
('DPS', '7198', 'Property, Main Market', 'DPS RESOURCES BHD', 'DPS'),
('KEINHIN', '7199', 'Industrial Products & Services, Main Market', 'KEIN HING INTERNATIONAL BHD', 'KEIN HING INTERNATIONAL'),
('TEKSENG', '7200', 'Consumer Products & Services, Main Market', 'TEK SENG HOLDINGS BHD', 'TEK SENG'),
('PICORP', '7201', 'Industrial Products & Services, Main Market', 'PROGRESSIVE IMPACT CORPORATION', 'PROGRESSIVE IMPACT'),
('CSCENIC', '7202', 'Consumer Products & Services, Main Market', 'CLASSIC SCENIC BHD', 'CLASSIC SCENIC'),
('WANGZNG', '7203', 'Consumer Products & Services, Main Market', 'WANG-ZHENG BHD', 'WANG-ZHENG'),
('D&O', '7204', 'Technology, Main Market', NULL, NULL),
('COCOLND', '7205', 'Consumer Products & Services, Main Market', 'COCOALAND HOLDINGS BHD', 'COCOALAND'),
('THHEAVY', '7206', 'Energy, Main Market', 'TH HEAVY ENGINEERING BERHAD', 'TH HEAVY ENGINEERING'),
('SUCCESS', '7207', 'Industrial Products & Services, Main Market', 'SUCCESS TRANSFORMER CORP BHD', 'SUCCESS TRANSFORMER CORP'),
('EURO', '7208', 'Consumer Products & Services, Main Market', 'EURO HOLDINGS BHD', 'EURO'),
('CHEETAH', '7209', 'Consumer Products & Services, Main Market', 'CHEETAH HOLDINGS BHD', 'CHEETAH'),
('FREIGHT', '7210', 'Transportation & Logistics, Main Market', 'FREIGHT MANAGEMENT HLDGS BHD', 'FREIGHT MANAGEMENT HLDGS'),
('TAFI', '7211', 'Consumer Products & Services, Main Market', 'TAFI INDUSTRIES BHD', 'TAFI'),
('DESTINI', '7212', 'Industrial Products & Services, Main Market', 'DESTINI BERHAD', 'DESTINI'),
('ARANK', '7214', 'Industrial Products & Services, Main Market', 'A-RANK BHD', 'A-RANK'),
('NIHSIN', '7215', 'Consumer Products & Services, Main Market', 'NI HSIN RESOURCES BHD', 'NI HSIN'),
('KAWAN', '7216', 'Consumer Products & Services, Main Market', 'KAWAN FOOD BHD', 'KAWAN FOOD'),
('EMETALL', '7217', 'Industrial Products & Services, Main Market', 'EONMETALL GROUP BHD', 'EONMETALL'),
('TOCEAN', '7218', 'Transportation & Logistics, Main Market', 'TRANSOCEAN HOLDINGS BHD', 'TRANSOCEAN'),
('MINETEC', '7219', 'Industrial Products & Services, Main Market', 'MINETECH RESOURCES BHD', 'MINETECH'),
('BSLCORP', '7221', 'Industrial Products & Services, Main Market', 'BSL CORPORATION BERHAD', 'BSL'),
('IMASPRO', '7222', 'Industrial Products & Services, Main Market', 'IMASPRO CORPORATION BHD', 'IMASPRO'),
('JADI', '7223', 'Consumer Products & Services, Main Market', 'JADI IMAGING HOLDINGS BHD', 'JADI IMAGING'),
('PA', '7225', 'Industrial Products & Services, Main Market', 'P.A. RESOURCES BHD', 'P.A.'),
('WATTA', '7226', 'Industrial Products & Services, Main Market', 'WATTA HOLDING BHD', 'WATTA HOLDING'),
('UMSNGB', '7227', 'Industrial Products & Services, Main Market', 'UMS-NEIKEN GROUP BHD', 'UMS-NEIKEN'),
('T7GLOBAL', '7228', 'Energy, Main Market', 'T7 GLOBAL BERHAD', 'T7 GLOBAL'),
('FAVCO', '7229', 'Industrial Products & Services, Main Market', 'FAVELLE FAVCO BHD', 'FAVELLE FAVCO'),
('TOMEI', '7230', 'Consumer Products & Services, Main Market', 'TOMEI CONSOLIDATED BHD', 'TOMEI CONSOLIDATED'),
('WELLCAL', '7231', 'Industrial Products & Services, Main Market', 'WELLCALL HOLDINGS BHD', 'WELLCALL'),
('RESINTC', '7232', 'Industrial Products & Services, Main Market', 'RESINTECH BHD', 'RESINTECH'),
('DUFU', '7233', 'Industrial Products & Services, Main Market', 'DUFU TECHNOLOGY CORP. BHD', 'DUFU TECHNOLOGY CORP.'),
('MESB', '7234', 'Consumer Products & Services, Main Market', 'MESB BHD', 'MESB'),
('SUPERLN', '7235', 'Industrial Products & Services, Main Market', 'SUPERLON HOLDINGS BHD', 'SUPERLON'),
('PWROOT', '7237', 'Consumer Products & Services, Main Market', 'POWER ROOT BERHAD', 'POWER ROOT'),
('SCNWOLF', '7239', 'Industrial Products & Services, Main Market', 'SCANWOLF CORPORATION BHD', 'SCANWOLF'),
('VERTICE', '7240', 'Consumer Products & Services, Main Market', 'VERTICE BERHAD', 'VERTICE'),
('NGGB', '7241', 'Industrial Products & Services, Main Market', 'NEXTGREEN GLOBAL BERHAD', 'NEXTGREEN GLOBAL'),
('BIOOSMO', '7243', 'Consumer Products & Services, Main Market', 'BIO OSMO BHD', 'BIO OSMO'),
('WZSATU', '7245', 'Industrial Products & Services, Main Market', 'WZ SATU BERHAD', 'WZ SATU'),
('SIGN', '7246', 'Consumer Products & Services, Main Market', 'SIGNATURE INTERNATIONAL BHD', 'SIGNATURE INTERNATIONAL'),
('SCGM', '7247', 'Industrial Products & Services, Main Market', 'SCGM BHD', 'SCGM'),
('SLP', '7248', 'Industrial Products & Services, Main Market', 'SLP RESOURCES BHD', 'SLP'),
('EWEIN', '7249', 'Property, Main Market', 'EWEIN BERHAD', 'EWEIN'),
('UZMA', '7250', 'Energy, Main Market', 'UZMA BHD', 'UZMA'),
('BARAKAH', '7251', 'Energy, Main Market', 'BARAKAH OFFSHORE PETROLEUM BHD', 'BARAKAH OFFSHORE PETROLEUM'),
('TEOSENG', '7252', 'Consumer Products & Services, Main Market', 'TEO SENG CAPITAL BHD', 'TEO SENG'),
('HANDAL', '7253', 'Energy, Main Market', 'HANDAL RESOURCES BERHAD', 'HANDAL'),
('DIALOG', '7277', 'Energy, Main Market', 'DIALOG GROUP BHD', 'DIALOG'),
('TOMYPAK', '7285', 'Industrial Products & Services, Main Market', 'TOMYPAK HOLDINGS BHD', 'TOMYPAK'),
('YINSON', '7293', 'Energy, Main Market', 'YINSON HOLDINGS BHD', 'YINSON'),
('AHB', '7315', 'Consumer Products & Services, Main Market', 'AHB HOLDINGS BHD', 'AHB'),
('KEN', '7323', 'Property, Main Market', 'KEN HOLDINGS BHD', 'KEN'),
('TIENWAH', '7374', 'Industrial Products & Services, Main Market', 'TIEN WAH PRESS HOLDINGS BHD', 'TIEN WAH'),
('GLBHD', '7382', 'Plantation, Main Market', 'GOLDEN LAND BERHAD', 'GOLDEN LAND'),
('SHH', '7412', 'Consumer Products & Services, Main Market', 'SHH RESOURCES HOLDINGS BHD', 'SHH'),
('TECGUAN', '7439', 'Consumer Products & Services, Main Market', 'TECK GUAN PERDANA BHD', 'TECK GUAN PERDANA'),
('EDEN', '7471', 'Utilities, Main Market', 'EDEN INC. BHD', 'EDEN INC.'),
('RALCO', '7498', 'Industrial Products & Services, Main Market', 'RALCO CORPORATION BHD', 'RALCO'),
('HARNLEN', '7501', 'Plantation, Main Market', 'HARN LEN CORPORATION BHD', 'HARN LEN'),
('DKLS', '7528', 'Construction, Main Market', 'DKLS INDUSTRIES BHD', 'DKLS'),
('QUALITY', '7544', 'Industrial Products & Services, Main Market', 'QUALITY CONCRETE HOLDINGS BHD', 'QUALITY CONCRETE'),
('AWC', '7579', 'Industrial Products & Services, Main Market', 'AWC BERHAD', 'AWC'),
('MGB', '7595', 'Construction, Main Market', 'MGB BERHAD', 'MGB'),
('AJIYA', '7609', 'Industrial Products & Services, Main Market', 'AJIYA BHD', 'AJIYA'),
('MAGNA', '7617', 'Property, Main Market', 'MAGNA PRIMA BHD', 'MAGNA PRIMA'),
('HAIO', '7668', 'Consumer Products & Services, Main Market', 'HAI-O ENTERPRISE BHD', 'HAI-O ENTERPRISE'),
('GUNUNG', '7676', 'Transportation & Logistics, Main Market', 'GUNUNG CAPITAL BERHAD', 'GUNUNG'),
('WIDETEC', '7692', 'Industrial Products & Services, Main Market', 'WIDETECH (M) BHD', 'WIDETECH (M)'),
('ASIABRN', '7722', 'Consumer Products & Services, Main Market', 'ASIA BRANDS BERHAD', 'ASIA BRANDS'),
('UPA', '7757', 'Consumer Products & Services, Main Market', 'UPA CORPORATION BHD', 'UPA'),
('RAPID', '7765', 'Property, Main Market', 'RAPID SYNERGY BHD', 'RAPID SYNERGY'),
('EPMB', '7773', 'Industrial Products & Services, Main Market', 'EP MANUFACTURING BHD', 'EP MANUFACTURING'),
('RUBEREX', '7803', 'Industrial Products & Services, Main Market', 'RUBBEREX CORPORATION (M) BHD', 'RUBBEREX  (M)'),
('SAPIND', '7811', 'Industrial Products & Services, Main Market', 'SAPURA INDUSTRIAL BHD', 'SAPURA USTRIAL'),
('TIMWELL', '7854', 'Industrial Products & Services, Main Market', 'TIMBERWELL BHD', 'TIMBERWELL'),
('THRIVEN', '7889', 'Property, Main Market', 'THRIVEN GLOBAL BERHAD', 'THRIVEN GLOBAL'),
('MILUX', '7935', 'Consumer Products & Services, Main Market', 'MILUX CORPORATION BHD', 'MILUX'),
('SNC', '7943', 'Consumer Products & Services, Main Market', 'SAND NISKO CAPITAL BERHAD', 'SAND NISKO'),
('CNASIA', '7986', 'Industrial Products & Services, Main Market', 'CN ASIA CORPORATION BHD', 'CN ASIA'),
('CFM', '8044', 'Industrial Products & Services, Main Market', 'COMPUTER FORMS (M) BHD', 'COMPUTER FORMS (M)'),
('CICB', '8052', 'Industrial Products & Services, Main Market', 'CENTRAL INDUSTRIAL CORPORATION', 'CENTRAL USTRIAL'),
('LEESK', '8079', 'Consumer Products & Services, Main Market', 'LEE SWEE KIAT GROUP BHD', 'LEE SWEE KIAT'),
('POLY', '8117', 'Industrial Products & Services, Main Market', 'POLY GLASS FIBRE (M) BHD', 'POLY GLASS FIBRE (M)'),
('DAIBOCI', '8125', 'Industrial Products & Services, Main Market', 'DAIBOCHI BERHAD', 'DAIBOCHI'),
('BHIC', '8133', 'Transportation & Logistics, Main Market', 'BOUSTEAD HEAVY INDUSTRIES CORP', 'BOUSTEAD HEAVY  CORP'),
('MJPERAK', '8141', 'Property, Main Market', 'MAJUPERAK HOLDINGS BHD', 'MAJUPERAK'),
('ATAIMS', '8176', 'Industrial Products & Services, Main Market', 'ATA IMS BERHAD', 'ATA IMS'),
('MERCURY', '8192', 'Construction, Main Market', 'MERCURY INDUSTRIES BHD', 'MERCURY'),
('ECOWLD', '8206', 'Property, Main Market', 'ECO WORLD DEVELOPMENT GROUP BERHAD', 'ECO WORLD DEVELOPMENT'),
('PPHB', '8273', 'Industrial Products & Services, Main Market', 'PUBLIC PACKAGES HOLDINGS BHD', 'PUBLIC PACKAGES'),
('KFM', '8303', 'Consumer Products & Services, Main Market', 'KUANTAN FLOUR MILLS BHD', 'KUANTAN FLOUR MILLS'),
('PESONA', '8311', 'Construction, Main Market', 'PESONA METRO HOLDINGS BHD', 'PESONA METRO'),
('DATAPRP', '8338', 'Technology, Main Market', 'DATAPREP HOLDINGS BHD', 'DATAPREP'),
('PRKCORP', '8346', 'Transportation & Logistics, Main Market', 'PERAK CORPORATION BHD', 'PERAK'),
('KYM', '8362', 'Industrial Products & Services, Main Market', 'KYM HOLDINGS BHD', 'KYM'),
('TNLOGIS', '8397', 'Transportation & Logistics, Main Market', 'TIONG NAM LOGISTICS HOLDINGS', 'TIONG NAM'),
('PANSAR', '8419', 'Industrial Products & Services, Main Market', 'PANSAR BERHAD', 'PANSAR'),
('CEPCO', '8435', 'Industrial Products & Services, Main Market', 'CONCRETE ENGINEERING PRODUCTS', 'CONCRETE ENGINEERING PRODUCTS'),
('HIL', '8443', 'Industrial Products & Services, Main Market', 'HIL INDUSTRIES BHD', 'HIL'),
('HWATAI', '8478', 'Consumer Products & Services, Main Market', 'HWA TAI INDUSTRIES BHD', 'HWA TAI'),
('LIONFIB', '8486', 'Industrial Products & Services, Main Market', 'LION FOREST INDUSTRIES BHD', 'LION FOREST'),
('LBICAP', '8494', 'Property, Main Market', 'LBI CAPITAL BHD', 'LBI'),
('TALIWRK', '8524', 'Utilities, Main Market', 'TALIWORKS CORPORATION BHD', 'TALIWORKS'),
('SINOTOP', '8532', 'Consumer Products & Services, Main Market', 'SINOTOP HOLDINGS BERHAD', 'SINOTOP'),
('SALCON', '8567', 'Utilities, Main Market', 'SALCON BHD', 'SALCON'),
('MAHSING', '8583', 'Property, Main Market', 'MAH SING GROUP BHD', 'MAH SING'),
('CRESBLD', '8591', 'Construction, Main Market', 'CREST BUILDER HOLDINGS BHD', 'CREST BUILDER'),
('FIHB', '8605', 'Consumer Products & Services, Main Market', 'FEDERAL INTERNATIONAL HOLDINGS BERHAD', 'FEDERAL INTERNATIONAL'),
('ENRA', '8613', 'Property, Main Market', 'ENRA GROUP BERHAD', 'ENRA'),
('LPI', '8621', 'Financial Services, Main Market', 'LPI CAPITAL BHD', 'LPI'),
('JASKITA', '8648', 'Industrial Products & Services, Main Market', 'JASA KITA BHD', 'JASA KITA'),
('SPSETIA', '8664', 'Property, Main Market', 'SP SETIA BHD', 'SP SETIA'),
('KAMDAR', '8672', 'Consumer Products & Services, Main Market', 'KAMDAR GROUP(M)BHD', 'KAMDAR (M)'),
('TEXCHEM', '8702', 'Industrial Products & Services, Main Market', 'TEXCHEM RESOURCES BHD', 'TEXCHEM'),
('LEWEKO', '8745', 'Industrial Products & Services, Main Market', 'LEWEKO RESOURCES BHD', 'LEWEKO'),
('BREM', '8761', 'Construction, Main Market', 'BREM HOLDINGS BHD', 'BREM'),
('IREKA', '8834', 'Construction, Main Market', 'IREKA CORPORATION BHD', 'IREKA'),
('PMETAL', '8869', 'Industrial Products & Services, Main Market', 'PRESS METAL ALUMINIUM HOLDINGS BERHAD', 'METAL ALUMINIUM'),
('EKOVEST', '8877', 'Construction, Main Market', 'EKOVEST BHD', 'EKOVEST'),
('AVI', '8885', 'Consumer Products & Services, Main Market', 'AVILLION BERHAD', 'AVILLION'),
('MKLAND', '8893', 'Property, Main Market', 'MK LAND HOLDINGS BHD', 'MK LAND'),
('EG', '8907', 'Industrial Products & Services, Main Market', 'EG INDUSTRIES BHD', 'EG'),
('JIANKUN', '8923', 'Property, Main Market', 'JIANKUN INTERNATIONAL BERHAD', 'JIANKUN INTERNATIONAL'),
('JERASIA', '8931', 'Consumer Products & Services, Main Market', 'JERASIA CAPITAL BHD', 'JERASIA'),
('PRLEXUS', '8966', 'Consumer Products & Services, Main Market', 'PROLEXUS BHD', 'PROLEXUS'),
('CEPAT', '8982', 'Plantation, Main Market', 'CEPATWAWASAN GROUP BHD', 'CEPATWAWASAN'),
('OMESTI', '9008', 'Technology, Main Market', 'OMESTI BHD', 'OMESTI'),
('EKSONS', '9016', 'Industrial Products & Services, Main Market', 'EKSONS CORPORATION BHD', 'EKSONS'),
('TSH', '9059', 'Plantation, Main Market', 'TSH RESOURCES BHD', 'TSH'),
('THETA', '9075', 'Technology, Main Market', 'THETA EDGE BERHAD', 'THETA EDGE'),
('JETSON', '9083', 'Industrial Products & Services, Main Market', 'KUMPULAN JETSON BHD', 'KUMPULAN JETSON'),
('EMICO', '9091', 'Consumer Products & Services, Main Market', 'EMICO HOLDINGS BHD', 'EMICO'),
('SANBUMI', '9113', 'Consumer Products & Services, Main Market', 'SANBUMI HOLDINGS BHD', 'SANBUMI'),
('KPSCB', '9121', 'Industrial Products & Services, Main Market', 'KPS CONSORTIUM BHD', 'KPS CONSORTIUM'),
('ADVPKG', '9148', 'Industrial Products & Services, Main Market', 'ADVANCED PACKAGING TECHNOLOGY', 'ADVANCED PACKAGING TECHNOLOGY'),
('FPI', '9172', 'Consumer Products & Services, Main Market', 'FORMOSA PROSONIC INDUSTRIES', 'FORMOSA PROSONIC'),
('LYSAGHT', '9199', 'Industrial Products & Services, Main Market', 'LYSAGHT GALVANIZED STEEL BHD', 'LYSAGHT GALVANIZED STEEL'),
('SCIB', '9237', 'Industrial Products & Services, Main Market', 'SARAWAK CONSOLIDATED IND BHD', 'SARAWAK CONSOLIDATED'),
('GADANG', '9261', 'Construction, Main Market', 'GADANG HOLDINGS BHD', 'GADANG'),
('BONIA', '9288', 'Consumer Products & Services, Main Market', 'BONIA CORPORATION BHD', 'BONIA'),
('RCECAP', '9296', 'Financial Services, Main Market', 'RCE CAPITAL BHD', 'RCE'),
('FITTERS', '9318', 'Industrial Products & Services, Main Market', 'FITTERS DIVERSIFIED BHD', 'FITTERS DIVERSIFIED'),
('LBALUM', '9326', 'Industrial Products & Services, Main Market', 'LB ALUMINIUM BHD', 'LB ALUMINIUM'),
('KESM', '9334', 'Technology, Main Market', 'KESM INDUSTRIES BHD', 'KESM'),
('ANZO', '9342', 'Industrial Products & Services, Main Market', 'ANZO HOLDINGS BERHAD', 'ANZO'),
('TGL', '9369', 'Consumer Products & Services, Main Market', 'TEO GUAN LEE CORPORATION BHD', 'TEO GUAN LEE'),
('FSBM', '9377', 'Technology, Main Market', 'FSBM HOLDINGS BHD', 'FSBM'),
('LAYHONG', '9385', 'Consumer Products & Services, Main Market', 'LAY HONG BHD', 'LAY HONG'),
('ITRONIC', '9393', 'Technology, Main Market', 'INDUSTRONICS BHD', 'USTRONICS'),
('PARAGON', '9407', 'Consumer Products & Services, Main Market', 'PARAGON UNION BHD', 'PARAGON UNION'),
('CWG', '9423', 'Consumer Products & Services, Main Market', 'CWG HOLDINGS BERHAD', 'CWG'),
('SJC', '9431', 'Telecommunications & Media, Main Market', 'SENI JAYA CORPORATION BHD', 'SENI JAYA'),
('KKB', '9466', 'Industrial Products & Services, Main Market', 'KKB ENGINEERING BHD', 'KKB ENGINEERING'),
('BRAHIMS', '9474', 'Consumer Products & Services, Main Market', 'BRAHIMS HOLDINGS BERHAD', 'BRAHIMS'),
('MUH', '9539', 'Property, Main Market', 'MULTI-USAGE HOLDINGS BHD', 'MULTI-USAGE'),
('MITRA', '9571', 'Construction, Main Market', 'MITRAJAYA HOLDINGS BHD', 'MITRAJAYA'),
('PTARAS', '9598', 'Construction, Main Market', 'PINTARAS JAYA BHD', 'PINTARAS JAYA'),
('HWGB', '9601', 'Industrial Products & Services, Main Market', 'HO WAH GENTING BHD', 'HO WAH GENTING'),
('LEBTECH', '9628', 'Construction, Main Market', 'LEBTECH BERHAD', 'LEBTECH'),
('WCT', '9679', 'Construction, Main Market', 'WCT HOLDINGS BERHAD', 'WCT'),
('IDEAL', '9687', 'Property, Main Market', 'IDEAL UNITED BINTANG INTERNATIONAL BERHAD', 'IDEAL UNITED BINTANG INTERNATIONAL'),
('PLS', '9695', 'Plantation, Main Market', 'PLS PLANTATIONS BERHAD', 'PLS PLANTATIONS'),
('SYCAL', '9717', 'Construction, Main Market', 'SYCAL VENTURES BHD', 'SYCAL VENTURES'),
('ROHAS', '9741', 'Industrial Products & Services, Main Market', 'ROHAS TECNIC BERHAD', 'ROHAS TECNIC'),
('SMCAP', '9776', 'Consumer Products & Services, Main Market', 'SINMAH CAPITAL BERHAD', 'SINMAH'),
('SEG', '9792', 'Consumer Products & Services, Main Market', 'SEG INTERNATIONAL BHD', 'SEG INTERNATIONAL'),
('NATWIDE', '9806', 'Transportation & Logistics, Main Market', 'NATIONWIDE EXPRESS HOLDINGS BERHAD', 'NATIONWIDE EX'),
('BERTAM', '9814', 'Property, Main Market', 'BERTAM ALLIANCE BHD', 'BERTAM ALLIANCE'),
('SAM', '9822', 'Industrial Products & Services, Main Market', 'SAM ENGINEERING & EQUIPMENT', 'SAM ENGINEERING & EQUIPMENT'),
('SUIWAH', '9865', 'Consumer Products & Services, Main Market', 'SUIWAH CORPORATION BHD', 'SUIWAH'),
('PRESTAR', '9873', 'Industrial Products & Services, Main Market', 'PRESTAR RESOURCES BHD', 'PRESTAR'),
('LSTEEL', '9881', 'Industrial Products & Services, Main Market', 'LEADER STEEL HOLDINGS BHD', 'LEADER STEEL'),
('BRIGHT', '9938', 'Industrial Products & Services, Main Market', 'BRIGHT PACKAGING INDUSTRY BHD', 'BRIGHT PACKAGING USTRY'),
('REX', '9946', 'Consumer Products & Services, Main Market', 'REX INDUSTRY BHD', 'REX USTRY'),
('RGTBHD', '9954', 'Industrial Products & Services, Main Market', 'RGT BERHAD', 'RGT'),
('GMUTUAL', '9962', 'Property, Main Market', 'GROMUTUAL BHD', 'GROMUTUAL'),
('PENSONI', '9997', 'Consumer Products & Services, Main Market', 'PENSONIC HOLDINGS BHD', 'PENSONIC');